/**
 * KELIN MD — Naruto enemy data
 * Used by nhunt.js. Each enemy is filtered by level before selection.
 */
export default [
  // ── Level 1-5 (Academy Student) ──────────────────────────────────────────
  {
    name: "Bandit",
    level: 1,
    hp: 60,
    maxHp: 60,
    chakra: 20,
    attack: 8,
    defense: 4,
    speed: 6,
    jutsu: [],
    xpReward: 20,
    ryoReward: 50,
  },
  {
    name: "Rogue Ninja",
    level: 3,
    hp: 80,
    maxHp: 80,
    chakra: 40,
    attack: 12,
    defense: 6,
    speed: 9,
    jutsu: ["basic_taijutsu"],
    xpReward: 35,
    ryoReward: 80,
  },
  // ── Level 5-15 (Genin) ───────────────────────────────────────────────────
  {
    name: "Forest Wolf",
    level: 5,
    hp: 100,
    maxHp: 100,
    chakra: 30,
    attack: 16,
    defense: 8,
    speed: 14,
    jutsu: [],
    xpReward: 50,
    ryoReward: 120,
  },
  {
    name: "Missing-nin",
    level: 8,
    hp: 130,
    maxHp: 130,
    chakra: 60,
    attack: 20,
    defense: 10,
    speed: 12,
    jutsu: ["shadow_clone"],
    xpReward: 70,
    ryoReward: 180,
  },
  {
    name: "Corrupted Chunin",
    level: 12,
    hp: 160,
    maxHp: 160,
    chakra: 80,
    attack: 24,
    defense: 14,
    speed: 15,
    jutsu: ["basic_taijutsu"],
    xpReward: 100,
    ryoReward: 250,
  },
  // ── Level 15-30 (Chunin) ─────────────────────────────────────────────────
  {
    name: "Akatsuki Grunt",
    level: 16,
    hp: 200,
    maxHp: 200,
    chakra: 110,
    attack: 30,
    defense: 18,
    speed: 18,
    jutsu: ["shadow_clone", "fireball"],
    xpReward: 140,
    ryoReward: 350,
  },
  {
    name: "Earth Spider",
    level: 20,
    hp: 240,
    maxHp: 240,
    chakra: 90,
    attack: 35,
    defense: 22,
    speed: 16,
    jutsu: [],
    xpReward: 175,
    ryoReward: 420,
  },
  {
    name: "Sand Puppet Master",
    level: 25,
    hp: 280,
    maxHp: 280,
    chakra: 140,
    attack: 40,
    defense: 26,
    speed: 20,
    jutsu: ["shadow_clone"],
    xpReward: 210,
    ryoReward: 500,
  },
  // ── Level 30-50 (Special Jonin / Jonin) ──────────────────────────────────
  {
    name: "Jonin Defector",
    level: 32,
    hp: 340,
    maxHp: 340,
    chakra: 180,
    attack: 48,
    defense: 32,
    speed: 28,
    jutsu: ["shadow_clone", "fireball"],
    xpReward: 260,
    ryoReward: 650,
  },
  {
    name: "Rogue Sensor Ninja",
    level: 40,
    hp: 400,
    maxHp: 400,
    chakra: 200,
    attack: 55,
    defense: 38,
    speed: 35,
    jutsu: ["shadow_clone"],
    xpReward: 330,
    ryoReward: 800,
  },
  {
    name: "Orochimaru's Minion",
    level: 48,
    hp: 460,
    maxHp: 460,
    chakra: 230,
    attack: 62,
    defense: 44,
    speed: 40,
    jutsu: ["fireball", "shadow_clone"],
    xpReward: 400,
    ryoReward: 1000,
  },
  // ── Level 50-75 (ANBU) ───────────────────────────────────────────────────
  {
    name: "Akatsuki Member",
    level: 55,
    hp: 550,
    maxHp: 550,
    chakra: 280,
    attack: 72,
    defense: 52,
    speed: 48,
    jutsu: ["shadow_clone", "fireball"],
    xpReward: 500,
    ryoReward: 1300,
  },
  {
    name: "Corrupted ANBU",
    level: 65,
    hp: 640,
    maxHp: 640,
    chakra: 320,
    attack: 82,
    defense: 60,
    speed: 55,
    jutsu: ["fireball", "shadow_clone"],
    xpReward: 600,
    ryoReward: 1600,
  },
  // ── Level 75-100 (Kage) ──────────────────────────────────────────────────
  {
    name: "Seven Swordsmen Remnant",
    level: 78,
    hp: 750,
    maxHp: 750,
    chakra: 360,
    attack: 94,
    defense: 70,
    speed: 65,
    jutsu: ["shadow_clone"],
    xpReward: 750,
    ryoReward: 2000,
  },
  {
    name: "Madara's Clone",
    level: 95,
    hp: 900,
    maxHp: 900,
    chakra: 450,
    attack: 110,
    defense: 85,
    speed: 78,
    jutsu: ["fireball", "shadow_clone"],
    xpReward: 950,
    ryoReward: 2500,
  },
  // ── Level 100+ (Legendary) ───────────────────────────────────────────────
  {
    name: "Zetsu",
    level: 105,
    hp: 1100,
    maxHp: 1100,
    chakra: 550,
    attack: 130,
    defense: 100,
    speed: 90,
    jutsu: ["shadow_clone", "fireball"],
    xpReward: 1200,
    ryoReward: 3200,
  },
];
