// lib/dragonball/techniques.js — DBZ techniques (replacing naruto jutsu)
// types: energy | support | physical | ultimate

export default [
  // ── Rank 1 (basic energy) ──────────────────────────────────────────────────
  {
    id: "double_sunday",
    name: "Double Sunday",
    type: "energy",
    rank: "1",
    level: 1,
    damage: 40,
    ki: 12,
    accuracy: 100,
    cooldown: 1,
    race: null,
    description: "Fire twin energy blasts at the opponent.",
  },
  {
    id: "renzoku_energy_dan",
    name: "Renzoku Energy Dan",
    type: "energy",
    rank: "1",
    level: 3,
    damage: 45,
    ki: 14,
    accuracy: 100,
    cooldown: 1,
    race: null,
    description: "Rapid-fire barrage of ki blasts.",
  },

  // ── Rank 2 ──────────────────────────────────────────────────────────────────
  {
    id: "destructo_disc",
    name: "Destructo Disc",
    type: "energy",
    rank: "2",
    level: 5,
    damage: 65,
    ki: 18,
    accuracy: 100,
    cooldown: 1,
    race: null,
    description: "A razor-sharp energy ring that cuts through most defenses.",
  },
  {
    id: "galick_gun",
    name: "Galick Gun",
    type: "energy",
    rank: "2",
    level: 8,
    damage: 72,
    ki: 24,
    accuracy: 100,
    cooldown: 2,
    race: "Saiyan",
    description: "A devastating purple energy beam from both hands.",
  },
  {
    id: "kamehameha",
    name: "Kamehameha",
    type: "energy",
    rank: "2",
    level: 5,
    damage: 75,
    ki: 25,
    accuracy: 100,
    cooldown: 2,
    race: null,
    description: "The iconic blue energy wave. KA-ME-HA-ME-HA!",
  },
  {
    id: "solar_flare",
    name: "Solar Flare",
    type: "support",
    rank: "2",
    level: 6,
    damage: 0,
    ki: 12,
    accuracy: 100,
    cooldown: 3,
    race: null,
    effect: "blind",
    description: "Blinds the opponent, reducing their next attack accuracy.",
  },
  {
    id: "energy_shield",
    name: "Energy Shield",
    type: "support",
    rank: "2",
    level: 8,
    damage: 0,
    ki: 20,
    accuracy: 100,
    cooldown: 3,
    race: null,
    effect: "defense_up",
    description: "Generate a ki barrier, boosting defense by 30% for 2 turns.",
  },

  // ── Rank 3 ──────────────────────────────────────────────────────────────────
  {
    id: "tri_beam",
    name: "Tri-Beam",
    type: "energy",
    rank: "3",
    level: 15,
    damage: 88,
    ki: 35,
    accuracy: 100,
    cooldown: 2,
    race: "Human",
    description: "An energy triangle that unleashes a devastating beam.",
  },
  {
    id: "hellzone_grenade",
    name: "Hellzone Grenade",
    type: "energy",
    rank: "3",
    level: 15,
    damage: 82,
    ki: 34,
    accuracy: 100,
    cooldown: 3,
    race: "Namekian",
    description: "Surround the enemy with energy spheres and detonate them all.",
  },
  {
    id: "special_beam_cannon",
    name: "Special Beam Cannon",
    type: "energy",
    rank: "3",
    level: 12,
    damage: 92,
    ki: 40,
    accuracy: 100,
    cooldown: 3,
    race: "Namekian",
    description: "A piercing spiral beam that ignores some defense.",
  },
  {
    id: "big_bang_attack",
    name: "Big Bang Attack",
    type: "energy",
    rank: "3",
    level: 20,
    damage: 95,
    ki: 44,
    accuracy: 100,
    cooldown: 3,
    race: "Saiyan",
    description: "A condensed sphere of energy that explodes on contact.",
  },

  // ── Rank 4 (ultimate) ──────────────────────────────────────────────────────
  {
    id: "final_flash",
    name: "Final Flash",
    type: "energy",
    rank: "4",
    level: 30,
    damage: 110,
    ki: 52,
    accuracy: 100,
    cooldown: 4,
    race: "Saiyan",
    description: "Vegeta's trademark golden super-blast. Pure destruction.",
  },
  {
    id: "death_ball",
    name: "Death Ball",
    type: "ultimate",
    rank: "4",
    level: 30,
    damage: 118,
    ki: 60,
    accuracy: 100,
    cooldown: 4,
    race: "Frieza Race",
    description: "A planet-destroying energy sphere from Frieza's arsenal.",
  },
  {
    id: "spirit_bomb",
    name: "Spirit Bomb",
    type: "ultimate",
    rank: "4",
    level: 35,
    damage: 140,
    ki: 72,
    accuracy: 100,
    cooldown: 5,
    race: null,
    description: "Gather energy from all living things to form a massive bomb.",
  },
  {
    id: "self_destruct",
    name: "Self Destruct",
    type: "ultimate",
    rank: "4",
    level: 25,
    damage: 220,
    ki: 100,
    accuracy: 100,
    cooldown: 10,
    race: "Android",
    selfDamage: 0.5,
    description: "Detonate your power cells — extreme damage but costs 50% of YOUR HP.",
  },
];
