const dares = [
  "Send a voice note singing your favorite song.",
  "Change your profile picture to a potato for 10 minutes.",
  "Send a 👍 emoji to the last 5 people you chatted with.",
  "Text 'I appreciate you!' to someone you haven't talked to in a while.",
  "Send a message using only emojis.",
  "Talk in all caps for the next 5 messages.",
  "Type with your eyes closed and don't correct mistakes.",
  "Reply to the next message with only 'Interesting.'",
  "Send a selfie making the funniest face you can.",
  "Change your WhatsApp bio to 'Professional banana inspector' for 10 minutes.",
  "Record yourself saying the alphabet backwards (or try).",
  "Send your favorite meme to the group.",
  "Compliment everyone in the group with one word.",
  "Use only GIFs for the next 5 minutes.",
  "Talk like a pirate for the next 10 messages.",
  "Pretend you're a robot in your next 5 replies.",
  "Send the oldest photo in your gallery.",
  "Send the newest photo in your gallery.",
  "Change your display name to 'Chicken Nugget' for 10 minutes.",
  "Describe yourself using only three emojis.",
  "Try to make everyone laugh with one message.",
  "Send a random fun fact.",
  "Write a four-line poem about pizza.",
  "Speak in rhymes for the next 5 messages.",
  "Message your best friend 'Guess what?' and don't reply for 5 minutes.",
  "Send a voice note laughing for 10 seconds.",
  "Write a short rap about yourself.",
  "Use only questions for your next 5 messages.",
  "Describe your day using movie titles.",
  "Spell your name backwards.",
  "Tell a terrible dad joke.",
  "Say something nice about the person who sent the last message.",
  "Send your favorite emoji 20 times.",
  "Use the word 'banana' in every sentence for 5 messages.",
  "Pretend to be a news reporter for your next message.",
  "Invent a new word and define it.",
  "Act like you're famous for the next 5 messages.",
  "Describe your favorite food without naming it.",
  "Send a picture of your shoes.",
  "Send a random picture from your camera roll.",
  "Type your next message with one hand.",
  "Talk like a baby for the next 5 messages.",
  "Write a compliment that rhymes.",
  "Name 10 countries in 20 seconds (honor system).",
  "Send a voice note in your best movie trailer voice.",
  "Make up a superhero name for yourself.",
  "Describe the person above you using only emojis.",
  "Change your status to 'Powered by Wi-Fi' for 10 minutes.",
  "Pretend you're an alien visiting Earth.",
  "Tell the group your favorite snack dramatically.",
  "Send the last screenshot you took.",
  "Balance a book on your head for 30 seconds.",
  "Do 10 jumping jacks and tell us how it went.",
  "Touch your toes for 30 seconds.",
  "Spin around 10 times before sending your next message.",
  "Sing 'Happy Birthday' in a voice note.",
  "Talk without using the letter 'E' for your next 3 messages.",
  "Write a slogan for toothpaste.",
  "Say the first word that comes to your mind.",
  "Describe your dream house in one sentence.",
  "Pretend you're the group's motivational speaker.",
  "Use an accent for your next voice note.",
  "Create a nickname for everyone in the group.",
  "Tell everyone your favorite movie quote.",
  "Write a sentence where every word starts with the same letter.",
  "Say 'I'm awesome' five times in a voice note.",
  "Draw a smiley face and send a picture of it.",
  "Send a picture of something blue near you.",
  "Post a random animal emoji every minute for 5 minutes.",
  "Write a fake advertisement for water.",
  "Describe your phone without saying its color.",
  "Use only one-word answers for 5 minutes.",
  "Pretend you're a teacher grading this group.",
  "Create a new holiday and explain it.",
  "Write a haiku about your day.",
  "Name five things that make you smile.",
  "Say something kind to the oldest person in the chat.",
  "Message someone 'Have an amazing day!'",
  "Pretend you're a detective solving a mystery.",
  "Write a fake weather forecast for tomorrow.",
  "Describe yourself like you're a video game character.",
  "Write a pickup line using fruit.",
  "Say the alphabet as fast as you can in a voice note.",
  "Use only animal sounds for your next 3 messages.",
  "Send your favorite quote.",
  "Tell everyone your favorite hobby.",
  "Write a movie title about your life.",
  "Describe your pet (or dream pet) dramatically.",
  "Pretend you're invisible for your next 5 messages.",
  "Tell the group your favorite dessert.",
  "Create a superhero catchphrase.",
  "Use only emojis to describe your mood.",
  "Tell everyone one random fact about yourself.",
  "Make up a tongue twister.",
  "Write a one-sentence horror story.",
  "Write a one-sentence comedy story.",
  "Pretend you're hosting an award show.",
  "Give yourself a funny title.",
  "Write the chorus of an imaginary song.",
  "Describe your room using only adjectives.",
  "Tell everyone what superpower you'd want.",
  "Send a voice note saying 'I accept the challenge!' dramatically.",
  "Pretend you're an AI trying to understand humans.",
  "Write a compliment to the entire group.",
  "Say your favorite food in the most dramatic way possible.",
  "End every message with 😎 for the next 10 minutes.",
  "Send a random positive affirmation.",
  "Describe your dream vacation using only emojis."
];

export default {
  name: "dare",
  description: "Get a random dare challenge",
  category: "fun",
  usage: ".dare",
  aliases: ["d"],
  cooldown: 5,
  isOwner: false,
  isAdmin: false,
  isPremium: false,
  version: "1.0.0",
  async run({ sock, msg }) {
    const dare = dares[Math.floor(Math.random() * dares.length)];
    await sock.sendMessage(msg.key.remoteJid, { text: `🎯 *Dare:* ${dare}` });
  },
};
