const jokes = [
  "Why don't scientists trust atoms? Because they make up everything!",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "Why can't your nose be 12 inches long? Because then it'd be a foot!",
  "What do you call fake spaghetti? An impasta.",
  "Why did the bicycle fall over? Because it was two-tired.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "What do you call cheese that isn't yours? Nacho cheese.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "Why did the math book look sad? Because it had too many problems.",
  "What do you call a bear with no teeth? A gummy bear.",
  "What kind of tree fits in your hand? A palm tree.",
  "Why was the broom late? It swept in.",
  "Why did the cookie go to the doctor? Because it felt crumbly.",
  "Why did the tomato blush? Because it saw the salad dressing.",
  "What do you call an alligator in a vest? An investigator.",
  "Why don't eggs tell jokes? They'd crack each other up.",
  "Why did the student eat his homework? Because the teacher said it was a piece of cake.",
  "Why did the coffee file a police report? It got mugged.",
  "What do you call a sleeping bull? A bulldozer.",
  "Why can't a leopard hide? Because it's always spotted.",
  "Why did the banana go to the doctor? It wasn't peeling well.",
  "What do you call a fish wearing a bowtie? Sofishticated.",
  "Why did the chicken join a band? Because it had drumsticks.",
  "What do you call a cow with no legs? Ground beef.",
  "What did one wall say to the other? I'll meet you at the corner.",
  "What kind of shoes do ninjas wear? Sneakers.",
  "Why did the stadium get hot? Because all the fans left.",
  "Why did the clock get kicked out? It kept tocking back.",
  "Why are ghosts bad liars? Because you can see right through them.",
  "What did one hat say to the other? Stay here, I'll go on ahead.",
  "Why was six afraid of seven? Because seven eight nine.",
  "What do you call a boomerang that won't come back? A stick.",
  "Why don't oysters donate to charity? Because they're shellfish.",
  "Why couldn't the pirate learn the alphabet? He got lost at C.",
];

export default {
  name: "joke",
  description: "Get a random programming joke",
  category: "fun",
  usage: ".joke",
  aliases: ["jk"],
  cooldown: 3,
  isOwner: false,
  isAdmin: false,
  isPremium: false,
  version: "1.0.0",
  async run({ sock, msg }) {
    const joke = jokes[Math.floor(Math.random() * jokes.length)];
    await sock.sendMessage(msg.key.remoteJid, { text: `😂 ${joke}` });
  },
};
