const truths = [
  "What's the most embarrassing thing you've ever texted the wrong person?",
  "Have you ever lied about your age?",
  "What's the weirdest dream you've ever had?",
  "Have you ever stalked someone's profile for more than 30 minutes?",
  "What's the longest you've gone without showering?",
  "Who was your first crush?",
  "Have you ever had a secret crush on a friend?",
  "What's your biggest fear?",
  "Have you ever cheated on a test?",
  "What's a secret you've never told your parents?",
  "Have you ever pretended to be sick to skip school or work?",
  "What's the biggest lie you've ever told?",
  "Who in this chat would you trust with your biggest secret?",
  "Have you ever cried over someone?",
  "What's your most awkward date story?",
  "What's your guilty pleasure?",
  "Have you ever been caught lying?",
  "Who do you miss the most right now?",
  "What's something you're glad your parents don't know?",
  "Have you ever had a fake account?",
  "Have you ever fallen asleep in class?",
  "What's the dumbest thing you've spent money on?",
  "Have you ever stolen something?",
  "What's your worst habit?",
  "Who was the last person you stalked online?",
  "Have you ever been rejected?",
  "What's the most childish thing you still do?",
  "Have you ever had a paranormal experience?",
  "What's your biggest insecurity?",
  "What's your biggest regret?",
  "Have you ever broken someone's heart?",
  "Has someone ever broken yours?",
  "What's something you've never admitted to anyone?",
  "What's your most embarrassing childhood memory?",
  "What's the meanest thing you've ever said to someone?",
  "Have you ever ghosted someone?",
  "What's something illegal you've done?",
  "Have you ever snooped through someone's phone?",
  "Have you ever blamed someone else for something you did?",
  "What's your biggest turn-off?",
  "What's your biggest turn-on?",
  "Who in this chat do you think is the funniest?",
  "Who in this chat do you think is the most attractive?",
  "Have you ever had a crush on a teacher?",
  "Have you ever liked your best friend's partner?",
  "What's the worst gift you've ever received?",
  "What's the weirdest food you've eaten?",
  "What's the strangest rumor you've heard about yourself?",
  "Have you ever cried during a movie?",
  "What's your biggest pet peeve?",
  "What's the most embarrassing thing your parents have caught you doing?",
  "What's something you're addicted to?",
  "Have you ever skipped class?",
  "What's the longest you've stayed awake?",
  "What's the worst trouble you've ever gotten into?",
  "Have you ever lied to your best friend?",
  "What's one thing you'd change about yourself?",
  "What's your biggest weakness?",
  "What's your biggest strength?",
  "Have you ever accidentally broken something expensive?",
  "What's your biggest flex?",
  "What's the worst haircut you've ever had?",
  "What's your most irrational fear?",
  "Who do you secretly admire?",
  "What's something you wish you were better at?",
  "Have you ever laughed at the wrong moment?",
  "What's your most embarrassing nickname?",
  "What's something you've done that you're proud of?",
  "What's your favorite memory?",
  "What's the weirdest thing you've searched online?",
  "What's the most embarrassing photo of you?",
  "What's the last thing that made you cry?",
  "Have you ever been friend-zoned?",
  "Have you ever put someone in the friend zone?",
  "What's your biggest red flag?",
  "Have you ever had a one-sided crush?",
  "What's your biggest green flag?",
  "Who was the last person you apologized to?",
  "Have you ever pretended to like a gift?",
  "What's the funniest lie you've ever believed?",
  "What's your biggest life goal?",
  "What's your worst cooking disaster?",
  "Have you ever sent a risky message and regretted it?",
  "What's the most embarrassing thing you've done in public?",
  "Have you ever had feelings for two people at once?",
  "What's your dream vacation?",
  "What's your most used emoji?",
  "What's your most embarrassing autocorrect fail?",
  "Have you ever been caught talking to yourself?",
  "What's your biggest achievement so far?",
  "If you had to marry someone in this chat, who would it be?",
  "If you could erase one memory, what would it be?",
  "What's one thing you wish you could tell your younger self?",
  "What's the funniest prank you've ever pulled?",
  "Have you ever accidentally called a teacher 'Mom' or 'Dad'?",
  "What's your worst fashion mistake?",
  "What's your most embarrassing social media post?",
  "Have you ever had a secret relationship?",
  "What's one thing you wish people knew about you?",
  "What's the last lie you told?",
  "Who do you think knows you best?",
  "If you could switch lives with anyone for a day, who would it be?",
  "What's one thing you can never forgive?",
  "What's your biggest motivation in life?",
  "What's something you've always wanted to try but never have?",
  "What's your most awkward family moment?",
  "Have you ever laughed so hard you cried?",
  "What's your weirdest talent?",
  "What's one thing you're secretly proud of?",
  "What's the most random compliment you've ever received?",
  "If today was your last day, who would you message first?"
];
export default {
  name: "truth",
  description: "Get a random truth question",
  category: "fun",
  usage: ".truth",
  aliases: ["t"],
  cooldown: 5,
  isOwner: false,
  isAdmin: false,
  isPremium: false,
  version: "1.0.0",
  async run({ sock, msg }) {
    const truth = truths[Math.floor(Math.random() * truths.length)];
    await sock.sendMessage(msg.key.remoteJid, { text: `🤔 *Truth:* ${truth}` });
  },
};
