export const GYMS = [
  {
    id: "tide",
    name: "Tide Gym",
    type: "Water",
    leader: "Mira",
    badge: "Tide Badge",
    description: "A rain-soaked arena where timing beats raw power.",
    theme: "tide",
    accent: "#50d7ff",
    background: "/battle-gym/tide.webp",
    music: "/battle-music/tide.mp3",
    rewardCoins: 25000,
    rewardXp: 1200,
    team: [
      { name: "swampert", pokedexId: 260, level: 28, types: ["water", "ground"], maxHp: 180, attack: 92, defense: 88, speed: 65, moves: [{ name: "Water Pulse", type: "water", power: 60, accuracy: 100, pp: 20 }, { name: "Mud Shot", type: "ground", power: 55, accuracy: 100, pp: 20 }] },
      { name: "gyarados", pokedexId: 130, level: 30, types: ["water", "flying"], maxHp: 195, attack: 105, defense: 82, speed: 81, moves: [{ name: "Aqua Tail", type: "water", power: 90, accuracy: 100, pp: 20 }, { name: "Bite", type: "dark", power: 60, accuracy: 100, pp: 20 }] },
      { name: "lapras", pokedexId: 131, level: 31, types: ["water", "ice"], maxHp: 210, attack: 96, defense: 90, speed: 60, moves: [{ name: "Ice Beam", type: "ice", power: 90, accuracy: 100, pp: 20 }, { name: "Water Pulse", type: "water", power: 60, accuracy: 100, pp: 20 }] },
      { name: "kingdra", pokedexId: 230, level: 32, types: ["water", "dragon"], maxHp: 205, attack: 110, defense: 98, speed: 85, moves: [{ name: "Dragon Pulse", type: "dragon", power: 85, accuracy: 100, pp: 20 }, { name: "Brine", type: "water", power: 65, accuracy: 100, pp: 20 }] },
      { name: "milotic", pokedexId: 350, level: 33, types: ["water"], maxHp: 225, attack: 102, defense: 105, speed: 86, moves: [{ name: "Surf", type: "water", power: 90, accuracy: 100, pp: 20 }, { name: "Ice Beam", type: "ice", power: 90, accuracy: 100, pp: 20 }] },
      { name: "greninja", pokedexId: 658, level: 35, types: ["water", "dark"], maxHp: 215, attack: 120, defense: 86, speed: 122, moves: [{ name: "Water Shuriken", type: "water", power: 75, accuracy: 100, pp: 20 }, { name: "Night Slash", type: "dark", power: 70, accuracy: 100, pp: 20 }] },
    ],
  },
  {
    id: "ember",
    name: "Ember Gym",
    type: "Fire",
    leader: "Kaida",
    badge: "Ember Badge",
    description: "A volcanic ring where every turn burns brighter.",
    theme: "ember",
    accent: "#ff886c",
    background: "/battle-gym/ember.webp",
    music: "/battle-music/ember.mp3",
    rewardCoins: 35000,
    rewardXp: 1800,
    unlockAfter: "tide",
    team: [
      { name: "arcanine", pokedexId: 59, level: 34, types: ["fire"], maxHp: 205, attack: 112, defense: 85, speed: 95, moves: [{ name: "Flame Wheel", type: "fire", power: 75, accuracy: 100, pp: 20 }, { name: "Bite", type: "dark", power: 60, accuracy: 100, pp: 20 }] },
      { name: "charizard", pokedexId: 6, level: 36, types: ["fire", "flying"], maxHp: 220, attack: 118, defense: 90, speed: 105, moves: [{ name: "Flamethrower", type: "fire", power: 90, accuracy: 100, pp: 20 }, { name: "Dragon Claw", type: "dragon", power: 80, accuracy: 100, pp: 20 }] },
      { name: "ninetales", pokedexId: 38, level: 35, types: ["fire"], maxHp: 190, attack: 104, defense: 86, speed: 100, moves: [{ name: "Fire Blast", type: "fire", power: 100, accuracy: 100, pp: 20 }, { name: "Confuse Ray", type: "ghost", power: 0, accuracy: 100, pp: 20 }] },
      { name: "volcarona", pokedexId: 637, level: 37, types: ["bug", "fire"], maxHp: 215, attack: 122, defense: 84, speed: 100, moves: [{ name: "Bug Buzz", type: "bug", power: 90, accuracy: 100, pp: 20 }, { name: "Flamethrower", type: "fire", power: 90, accuracy: 100, pp: 20 }] },
      { name: "talonflame", pokedexId: 663, level: 38, types: ["fire", "flying"], maxHp: 200, attack: 126, defense: 78, speed: 126, moves: [{ name: "Brave Bird", type: "flying", power: 100, accuracy: 100, pp: 20 }, { name: "Flame Charge", type: "fire", power: 50, accuracy: 100, pp: 20 }] },
      { name: "blaziken", pokedexId: 257, level: 40, types: ["fire", "fighting"], maxHp: 230, attack: 135, defense: 92, speed: 95, moves: [{ name: "Blaze Kick", type: "fire", power: 85, accuracy: 100, pp: 20 }, { name: "Brick Break", type: "fighting", power: 75, accuracy: 100, pp: 20 }] },
    ],
  },
  {
    id: "voltage",
    name: "Voltage Gym",
    type: "Electric",
    leader: "Volt",
    badge: "Voltage Badge",
    description: "Neon rails, charged platforms, and lightning-fast turns.",
    theme: "voltage",
    accent: "#ffe66d",
    background: "/battle-gym/voltage.webp",
    music: "/battle-music/voltage.mp3",
    rewardCoins: 50000,
    rewardXp: 2400,
    unlockAfter: "ember",
    team: [
      { name: "luxray", pokedexId: 405, level: 40, types: ["electric"], maxHp: 230, attack: 125, defense: 95, speed: 88, moves: [{ name: "Spark", type: "electric", power: 65, accuracy: 100, pp: 20 }, { name: "Crunch", type: "dark", power: 80, accuracy: 100, pp: 20 }] },
      { name: "zeraora", pokedexId: 807, level: 42, types: ["electric"], maxHp: 245, attack: 135, defense: 92, speed: 125, moves: [{ name: "Thunder Punch", type: "electric", power: 75, accuracy: 100, pp: 20 }, { name: "Slash", type: "normal", power: 70, accuracy: 100, pp: 20 }] },
      { name: "ampharos", pokedexId: 181, level: 41, types: ["electric"], maxHp: 240, attack: 118, defense: 100, speed: 72, moves: [{ name: "Thunderbolt", type: "electric", power: 90, accuracy: 100, pp: 20 }, { name: "Dragon Pulse", type: "dragon", power: 85, accuracy: 100, pp: 20 }] },
      { name: "magnezone", pokedexId: 462, level: 42, types: ["electric", "steel"], maxHp: 250, attack: 125, defense: 128, speed: 60, moves: [{ name: "Flash Cannon", type: "steel", power: 80, accuracy: 100, pp: 20 }, { name: "Thunderbolt", type: "electric", power: 90, accuracy: 100, pp: 20 }] },
      { name: "rotom", pokedexId: 479, level: 43, types: ["electric", "ghost"], maxHp: 220, attack: 118, defense: 100, speed: 110, moves: [{ name: "Shock Wave", type: "electric", power: 60, accuracy: 100, pp: 20 }, { name: "Shadow Ball", type: "ghost", power: 80, accuracy: 100, pp: 20 }] },
      { name: "electivire", pokedexId: 466, level: 44, types: ["electric"], maxHp: 255, attack: 140, defense: 94, speed: 100, moves: [{ name: "Thunder Punch", type: "electric", power: 75, accuracy: 100, pp: 20 }, { name: "Brick Break", type: "fighting", power: 75, accuracy: 100, pp: 20 }] },
    ],
  },
  {
    id: "shadow",
    name: "Shadow Gym",
    type: "Ghost",
    leader: "Noctis",
    badge: "Shadow Badge",
    description: "A moonlit ruin filled with illusions and spectral wind.",
    theme: "shadow",
    accent: "#c59bff",
    background: "/battle-gym/shadow.webp",
    music: "/battle-music/shadow.mp3",
    rewardCoins: 75000,
    rewardXp: 3200,
    unlockAfter: "voltage",
    team: [
      { name: "gengar", pokedexId: 94, level: 46, types: ["ghost", "poison"], maxHp: 235, attack: 120, defense: 85, speed: 118, moves: [{ name: "Shadow Ball", type: "ghost", power: 80, accuracy: 100, pp: 20 }, { name: "Sludge Bomb", type: "poison", power: 90, accuracy: 100, pp: 20 }] },
      { name: "dragapult", pokedexId: 887, level: 48, types: ["dragon", "ghost"], maxHp: 250, attack: 140, defense: 92, speed: 142, moves: [{ name: "Dragon Darts", type: "dragon", power: 90, accuracy: 100, pp: 20 }, { name: "Phantom Force", type: "ghost", power: 100, accuracy: 100, pp: 20 }] },
      { name: "mimikyu", pokedexId: 778, level: 47, types: ["ghost", "fairy"], maxHp: 220, attack: 126, defense: 98, speed: 105, moves: [{ name: "Shadow Claw", type: "ghost", power: 70, accuracy: 100, pp: 20 }, { name: "Play Rough", type: "fairy", power: 90, accuracy: 100, pp: 20 }] },
      { name: "chandelure", pokedexId: 609, level: 48, types: ["ghost", "fire"], maxHp: 235, attack: 135, defense: 92, speed: 100, moves: [{ name: "Shadow Ball", type: "ghost", power: 80, accuracy: 100, pp: 20 }, { name: "Flamethrower", type: "fire", power: 90, accuracy: 100, pp: 20 }] },
      { name: "aegislash", pokedexId: 681, level: 49, types: ["steel", "ghost"], maxHp: 255, attack: 145, defense: 135, speed: 60, moves: [{ name: "Iron Head", type: "steel", power: 80, accuracy: 100, pp: 20 }, { name: "Shadow Sneak", type: "ghost", power: 40, accuracy: 100, pp: 20 }] },
      { name: "giratina", pokedexId: 487, level: 52, types: ["ghost", "dragon"], maxHp: 290, attack: 152, defense: 140, speed: 90, moves: [{ name: "Shadow Force", type: "ghost", power: 100, accuracy: 100, pp: 20 }, { name: "Dragon Claw", type: "dragon", power: 80, accuracy: 100, pp: 20 }] },
    ],
  },
  {
    id: "frost",
    name: "Frost Gym",
    type: "Ice",
    leader: "Haku",
    badge: "Frost Badge",
    description: "A crystalline stadium where every mistake becomes a blizzard.",
    theme: "frost",
    accent: "#b8f1ff",
    background: "/battle-gym/frost.webp",
    music: "/battle-music/frost.mp3",
    rewardCoins: 110000,
    rewardXp: 4800,
    unlockAfter: "shadow",
    team: [
      { name: "mamoswine", pokedexId: 473, level: 56, types: ["ice", "ground"], maxHp: 310, attack: 168, defense: 125, speed: 80, moves: [{ name: "Icicle Crash", type: "ice", power: 95, accuracy: 100, pp: 20 }, { name: "Earthquake", type: "ground", power: 100, accuracy: 100, pp: 20 }] },
      { name: "froslass", pokedexId: 478, level: 57, types: ["ice", "ghost"], maxHp: 245, attack: 150, defense: 105, speed: 125, moves: [{ name: "Ice Beam", type: "ice", power: 90, accuracy: 100, pp: 20 }, { name: "Shadow Ball", type: "ghost", power: 80, accuracy: 100, pp: 20 }] },
      { name: "weavile", pokedexId: 461, level: 58, types: ["dark", "ice"], maxHp: 255, attack: 178, defense: 102, speed: 140, moves: [{ name: "Ice Punch", type: "ice", power: 75, accuracy: 100, pp: 20 }, { name: "Night Slash", type: "dark", power: 70, accuracy: 100, pp: 20 }] },
      { name: "baxcalibur", pokedexId: 998, level: 60, types: ["dragon", "ice"], maxHp: 330, attack: 185, defense: 140, speed: 98, moves: [{ name: "Icicle Spear", type: "ice", power: 85, accuracy: 100, pp: 20 }, { name: "Dragon Claw", type: "dragon", power: 80, accuracy: 100, pp: 20 }] },
      { name: "ninetales", pokedexId: 38, level: 59, types: ["ice", "fairy"], maxHp: 270, attack: 158, defense: 118, speed: 120, moves: [{ name: "Dazzling Gleam", type: "fairy", power: 80, accuracy: 100, pp: 20 }, { name: "Blizzard", type: "ice", power: 110, accuracy: 100, pp: 20 }] },
      { name: "kyurem", pokedexId: 646, level: 62, types: ["dragon", "ice"], maxHp: 360, attack: 205, defense: 158, speed: 105, moves: [{ name: "Glaciate", type: "ice", power: 95, accuracy: 100, pp: 20 }, { name: "Dragon Pulse", type: "dragon", power: 85, accuracy: 100, pp: 20 }] },
    ],
  },
  {
    id: "dragon",
    name: "Dragon Gym",
    type: "Dragon",
    leader: "Dray",
    badge: "Dragon Badge",
    description: "The final gate before the championship, built for elite trainers only.",
    theme: "dragon",
    accent: "#cf9bff",
    background: "/battle-gym/dragon.webp",
    music: "/battle-music/dragon.mp3",
    rewardCoins: 175000,
    rewardXp: 7200,
    unlockAfter: "frost",
    team: [
      { name: "dragonite", pokedexId: 149, level: 64, types: ["dragon", "flying"], maxHp: 370, attack: 205, defense: 155, speed: 100, moves: [{ name: "Dragon Claw", type: "dragon", power: 80, accuracy: 100, pp: 20 }, { name: "Hurricane", type: "flying", power: 95, accuracy: 100, pp: 20 }] },
      { name: "salamence", pokedexId: 373, level: 65, types: ["dragon", "flying"], maxHp: 360, attack: 215, defense: 145, speed: 125, moves: [{ name: "Dragon Rush", type: "dragon", power: 100, accuracy: 100, pp: 20 }, { name: "Fly", type: "flying", power: 90, accuracy: 100, pp: 20 }] },
      { name: "goodra", pokedexId: 706, level: 65, types: ["dragon"], maxHp: 390, attack: 190, defense: 165, speed: 92, moves: [{ name: "Muddy Water", type: "water", power: 90, accuracy: 100, pp: 20 }, { name: "Dragon Pulse", type: "dragon", power: 85, accuracy: 100, pp: 20 }] },
      { name: "dragapult", pokedexId: 887, level: 67, types: ["dragon", "ghost"], maxHp: 350, attack: 225, defense: 140, speed: 160, moves: [{ name: "Dragon Darts", type: "dragon", power: 90, accuracy: 100, pp: 20 }, { name: "Phantom Force", type: "ghost", power: 100, accuracy: 100, pp: 20 }] },
      { name: "garchomp", pokedexId: 445, level: 68, types: ["dragon", "ground"], maxHp: 380, attack: 230, defense: 165, speed: 125, moves: [{ name: "Earthquake", type: "ground", power: 100, accuracy: 100, pp: 20 }, { name: "Dragon Claw", type: "dragon", power: 80, accuracy: 100, pp: 20 }] },
      { name: "rayquaza", pokedexId: 384, level: 72, types: ["dragon", "flying"], maxHp: 450, attack: 260, defense: 190, speed: 145, moves: [{ name: "Dragon Ascent", type: "flying", power: 120, accuracy: 100, pp: 20 }, { name: "Outrage", type: "dragon", power: 120, accuracy: 100, pp: 20 }] },
    ],
  },
  {
    id: "psychic",
    name: "Psychic Gym",
    type: "Psychic",
    leader: "Selene",
    badge: "Mind Badge",
    description: "A gravity-bending arena where prediction matters more than speed.",
    theme: "psychic",
    accent: "#f08ad8",
    background: "/battle-gym/psychic.webp",
    music: "/battle-music/psychic.mp3",
    rewardCoins: 240000,
    rewardXp: 9800,
    unlockAfter: "dragon",
    team: [
      { name: "metagross", pokedexId: 376, level: 76, types: ["steel", "psychic"], maxHp: 470, attack: 270, defense: 250, speed: 95, moves: [{ name: "Meteor Mash", type: "steel", power: 100, accuracy: 100, pp: 20 }, { name: "Zen Headbutt", type: "psychic", power: 80, accuracy: 100, pp: 20 }] },
      { name: "alakazam", pokedexId: 65, level: 77, types: ["psychic"], maxHp: 330, attack: 285, defense: 115, speed: 180, moves: [{ name: "Psychic", type: "psychic", power: 90, accuracy: 100, pp: 20 }, { name: "Focus Blast", type: "fighting", power: 120, accuracy: 100, pp: 20 }] },
      { name: "gardevoir", pokedexId: 282, level: 78, types: ["psychic", "fairy"], maxHp: 390, attack: 260, defense: 155, speed: 125, moves: [{ name: "Moonblast", type: "fairy", power: 95, accuracy: 100, pp: 20 }, { name: "Psychic", type: "psychic", power: 90, accuracy: 100, pp: 20 }] },
      { name: "malamar", pokedexId: 687, level: 78, types: ["dark", "psychic"], maxHp: 410, attack: 245, defense: 180, speed: 100, moves: [{ name: "Psycho Cut", type: "psychic", power: 70, accuracy: 100, pp: 20 }, { name: "Night Slash", type: "dark", power: 70, accuracy: 100, pp: 20 }] },
      { name: "slowbro", pokedexId: 80, level: 79, types: ["water", "psychic"], maxHp: 520, attack: 220, defense: 270, speed: 45, moves: [{ name: "Psychic", type: "psychic", power: 90, accuracy: 100, pp: 20 }, { name: "Scald", type: "water", power: 80, accuracy: 100, pp: 20 }] },
      { name: "mewtwo", pokedexId: 150, level: 82, types: ["psychic"], maxHp: 560, attack: 325, defense: 210, speed: 190, moves: [{ name: "Psystrike", type: "psychic", power: 110, accuracy: 100, pp: 20 }, { name: "Aura Sphere", type: "fighting", power: 90, accuracy: 100, pp: 20 }] },
    ],
  },
  {
    id: "steel",
    name: "Steel Gym",
    type: "Steel",
    leader: "Forge",
    badge: "Alloy Badge",
    description: "An ironclad trial built to break unprepared teams.",
    theme: "steel",
    accent: "#a9c4d8",
    background: "/battle-gym/steel.webp",
    music: "/battle-music/steel.mp3",
    rewardCoins: 320000,
    rewardXp: 12500,
    unlockAfter: "psychic",
    team: [
      { name: "skarmory", pokedexId: 227, level: 83, types: ["steel", "flying"], maxHp: 430, attack: 235, defense: 300, speed: 110, moves: [{ name: "Iron Head", type: "steel", power: 80, accuracy: 100, pp: 20 }, { name: "Brave Bird", type: "flying", power: 100, accuracy: 100, pp: 20 }] },
      { name: "excadrill", pokedexId: 530, level: 84, types: ["ground", "steel"], maxHp: 455, attack: 305, defense: 185, speed: 145, moves: [{ name: "Iron Head", type: "steel", power: 80, accuracy: 100, pp: 20 }, { name: "Earthquake", type: "ground", power: 100, accuracy: 100, pp: 20 }] },
      { name: "scizor", pokedexId: 212, level: 85, types: ["bug", "steel"], maxHp: 440, attack: 300, defense: 230, speed: 115, moves: [{ name: "Bullet Punch", type: "steel", power: 70, accuracy: 100, pp: 20 }, { name: "X-Scissor", type: "bug", power: 80, accuracy: 100, pp: 20 }] },
      { name: "aegislash", pokedexId: 681, level: 86, types: ["steel", "ghost"], maxHp: 470, attack: 310, defense: 290, speed: 80, moves: [{ name: "Iron Head", type: "steel", power: 80, accuracy: 100, pp: 20 }, { name: "Shadow Sneak", type: "ghost", power: 60, accuracy: 100, pp: 20 }] },
      { name: "corviknight", pokedexId: 823, level: 87, types: ["flying", "steel"], maxHp: 500, attack: 260, defense: 285, speed: 90, moves: [{ name: "Iron Head", type: "steel", power: 80, accuracy: 100, pp: 20 }, { name: "Drill Peck", type: "flying", power: 80, accuracy: 100, pp: 20 }] },
      { name: "melmetal", pokedexId: 809, level: 90, types: ["steel"], maxHp: 650, attack: 360, defense: 320, speed: 55, moves: [{ name: "Double Iron Bash", type: "steel", power: 100, accuracy: 100, pp: 20 }, { name: "Rock Slide", type: "rock", power: 75, accuracy: 100, pp: 20 }] },
    ],
  },
  {
    id: "apex",
    name: "Apex Gym",
    type: "Champion",
    leader: "Orion",
    badge: "Apex Badge",
    description: "The final gym trial: a mixed team designed for championship contenders.",
    theme: "apex",
    accent: "#ffd36a",
    background: "/battle-gym/apex.webp",
    music: "/battle-music/apex.mp3",
    rewardCoins: 500000,
    rewardXp: 20000,
    unlockAfter: "steel",
    team: [
      { name: "tyranitar", pokedexId: 248, level: 92, types: ["rock", "dark"], maxHp: 610, attack: 350, defense: 300, speed: 95, moves: [{ name: "Stone Edge", type: "rock", power: 100, accuracy: 100, pp: 20 }, { name: "Crunch", type: "dark", power: 80, accuracy: 100, pp: 20 }] },
      { name: "volcarona", pokedexId: 637, level: 93, types: ["bug", "fire"], maxHp: 500, attack: 320, defense: 210, speed: 150, moves: [{ name: "Fiery Dance", type: "fire", power: 80, accuracy: 100, pp: 20 }, { name: "Bug Buzz", type: "bug", power: 90, accuracy: 100, pp: 20 }] },
      { name: "garchomp", pokedexId: 445, level: 94, types: ["dragon", "ground"], maxHp: 590, attack: 355, defense: 270, speed: 165, moves: [{ name: "Earthquake", type: "ground", power: 100, accuracy: 100, pp: 20 }, { name: "Dragon Claw", type: "dragon", power: 80, accuracy: 100, pp: 20 }] },
      { name: "zacian", pokedexId: 888, level: 95, types: ["fairy", "steel"], maxHp: 570, attack: 380, defense: 250, speed: 190, moves: [{ name: "Behemoth Blade", type: "steel", power: 100, accuracy: 100, pp: 20 }, { name: "Play Rough", type: "fairy", power: 90, accuracy: 100, pp: 20 }] },
      { name: "miraidon", pokedexId: 1008, level: 96, types: ["electric", "dragon"], maxHp: 600, attack: 370, defense: 260, speed: 180, moves: [{ name: "Electro Drift", type: "electric", power: 100, accuracy: 100, pp: 20 }, { name: "Dragon Pulse", type: "dragon", power: 85, accuracy: 100, pp: 20 }] },
      { name: "arceus", pokedexId: 493, level: 100, types: ["normal"], maxHp: 720, attack: 420, defense: 360, speed: 200, moves: [{ name: "Judgment", type: "normal", power: 120, accuracy: 100, pp: 20 }, { name: "Recover", type: "normal", power: 0, accuracy: 100, pp: 20 }] },
    ],
  },
  {
    id: "terra",
    name: "Terra Gym",
    type: "Ground",
    leader: "Gaia",
    badge: "Terra Badge",
    description: "A shifting canyon arena where sturdy teams outlast every storm.",
    theme: "terra",
    accent: "#d7a66a",
    background: "/battle-gym/viridian_gym.png",
    music: "/battle-music/mus_vs_gym_leader.mp3",
    rewardCoins: 600000,
    rewardXp: 24000,
    unlockAfter: "apex",
    team: [
      { name: "hippowdon", pokedexId: 450, level: 96, types: ["ground"], maxHp: 620, attack: 360, defense: 150, speed: 70, moves: [{ name: "Earthquake", type: "ground", power: 100, accuracy: 100, pp: 20 }, { name: "Stone Edge", type: "rock", power: 100, accuracy: 100, pp: 20 }] },
      { name: "gliscor", pokedexId: 472, level: 97, types: ["ground", "flying"], maxHp: 500, attack: 330, defense: 210, speed: 125, moves: [{ name: "Earthquake", type: "ground", power: 100, accuracy: 100, pp: 20 }, { name: "Stone Edge", type: "rock", power: 100, accuracy: 100, pp: 20 }] },
      { name: "mamoswine", pokedexId: 473, level: 98, types: ["ice", "ground"], maxHp: 650, attack: 340, defense: 240, speed: 95, moves: [{ name: "Hurricane", type: "flying", power: 110, accuracy: 100, pp: 20 }, { name: "Brave Bird", type: "flying", power: 100, accuracy: 100, pp: 20 }] },
      { name: "excadrill", pokedexId: 530, level: 99, types: ["ground", "steel"], maxHp: 610, attack: 370, defense: 220, speed: 150, moves: [{ name: "Earthquake", type: "ground", power: 100, accuracy: 100, pp: 20 }, { name: "Stone Edge", type: "rock", power: 100, accuracy: 100, pp: 20 }] },
      { name: "groudon", pokedexId: 383, level: 100, types: ["ground"], maxHp: 820, attack: 430, defense: 300, speed: 120, moves: [{ name: "Earthquake", type: "ground", power: 100, accuracy: 100, pp: 20 }, { name: "Stone Edge", type: "rock", power: 100, accuracy: 100, pp: 20 }] },
      { name: "landorus", pokedexId: 645, level: 102, types: ["ground", "flying"], maxHp: 760, attack: 420, defense: 330, speed: 145, moves: [{ name: "Earthquake", type: "ground", power: 100, accuracy: 100, pp: 20 }, { name: "Stone Edge", type: "rock", power: 100, accuracy: 100, pp: 20 }] },
    ],
  },
  {
    id: "toxic",
    name: "Toxic Gym",
    type: "Poison",
    leader: "Vesper",
    badge: "Venom Badge",
    description: "A neon laboratory where status effects and patience decide the match.",
    theme: "toxic",
    accent: "#b5f36c",
    background: "/battle-gym/viridian_gym.png",
    music: "/battle-music/mus_vs_gym_leader.mp3",
    rewardCoins: 720000,
    rewardXp: 29000,
    unlockAfter: "terra",
    team: [
      { name: "crobat", pokedexId: 169, level: 104, types: ["poison", "flying"], maxHp: 540, attack: 260, defense: 180, speed: 180, moves: [{ name: "Sludge Bomb", type: "poison", power: 90, accuracy: 100, pp: 20 }, { name: "Toxic", type: "poison", power: 0, accuracy: 100, pp: 20 }] },
      { name: "toxtricity", pokedexId: 849, level: 105, types: ["electric", "poison"], maxHp: 590, attack: 320, defense: 210, speed: 135, moves: [{ name: "Hurricane", type: "flying", power: 110, accuracy: 100, pp: 20 }, { name: "Brave Bird", type: "flying", power: 100, accuracy: 100, pp: 20 }] },
      { name: "nidoqueen", pokedexId: 31, level: 106, types: ["poison", "ground"], maxHp: 640, attack: 350, defense: 250, speed: 105, moves: [{ name: "Sludge Bomb", type: "poison", power: 90, accuracy: 100, pp: 20 }, { name: "Toxic", type: "poison", power: 0, accuracy: 100, pp: 20 }] },
      { name: "salazzle", pokedexId: 758, level: 107, types: ["poison", "fire"], maxHp: 520, attack: 300, defense: 180, speed: 160, moves: [{ name: "Sludge Bomb", type: "poison", power: 90, accuracy: 100, pp: 20 }, { name: "Toxic", type: "poison", power: 0, accuracy: 100, pp: 20 }] },
      { name: "overqwil", pokedexId: 904, level: 108, types: ["dark", "poison"], maxHp: 610, attack: 330, defense: 260, speed: 125, moves: [{ name: "Hurricane", type: "flying", power: 110, accuracy: 100, pp: 20 }, { name: "Brave Bird", type: "flying", power: 100, accuracy: 100, pp: 20 }] },
      { name: "eternatus", pokedexId: 890, level: 110, types: ["poison", "dragon"], maxHp: 900, attack: 460, defense: 390, speed: 160, moves: [{ name: "Sludge Bomb", type: "poison", power: 90, accuracy: 100, pp: 20 }, { name: "Toxic", type: "poison", power: 0, accuracy: 100, pp: 20 }] },
    ],
  },
  {
    id: "fairy",
    name: "Fairy Gym",
    type: "Fairy",
    leader: "Lumi",
    badge: "Radiant Badge",
    description: "A starlit hall where clever charms punish reckless attacks.",
    theme: "fairy",
    accent: "#ff9edb",
    background: "/battle-gym/viridian_gym.png",
    music: "/battle-music/mus_vs_gym_leader.mp3",
    rewardCoins: 850000,
    rewardXp: 34000,
    unlockAfter: "toxic",
    team: [
      { name: "mimikyu", pokedexId: 778, level: 112, types: ["ghost", "fairy"], maxHp: 520, attack: 300, defense: 250, speed: 120, moves: [{ name: "Hurricane", type: "flying", power: 110, accuracy: 100, pp: 20 }, { name: "Brave Bird", type: "flying", power: 100, accuracy: 100, pp: 20 }] },
      { name: "togekiss", pokedexId: 468, level: 113, types: ["fairy", "flying"], maxHp: 620, attack: 320, defense: 280, speed: 115, moves: [{ name: "Moonblast", type: "fairy", power: 95, accuracy: 100, pp: 20 }, { name: "Play Rough", type: "fairy", power: 90, accuracy: 100, pp: 20 }] },
      { name: "grimmsnarl", pokedexId: 861, level: 114, types: ["dark", "fairy"], maxHp: 680, attack: 380, defense: 300, speed: 95, moves: [{ name: "Hurricane", type: "flying", power: 110, accuracy: 100, pp: 20 }, { name: "Brave Bird", type: "flying", power: 100, accuracy: 100, pp: 20 }] },
      { name: "azumarill", pokedexId: 184, level: 115, types: ["water", "fairy"], maxHp: 700, attack: 350, defense: 330, speed: 80, moves: [{ name: "Hurricane", type: "flying", power: 110, accuracy: 100, pp: 20 }, { name: "Brave Bird", type: "flying", power: 100, accuracy: 100, pp: 20 }] },
      { name: "sylveon", pokedexId: 700, level: 116, types: ["fairy"], maxHp: 650, attack: 340, defense: 300, speed: 120, moves: [{ name: "Moonblast", type: "fairy", power: 95, accuracy: 100, pp: 20 }, { name: "Play Rough", type: "fairy", power: 90, accuracy: 100, pp: 20 }] },
      { name: "xerneas", pokedexId: 716, level: 118, types: ["fairy"], maxHp: 900, attack: 460, defense: 380, speed: 150, moves: [{ name: "Moonblast", type: "fairy", power: 95, accuracy: 100, pp: 20 }, { name: "Play Rough", type: "fairy", power: 90, accuracy: 100, pp: 20 }] },
    ],
  },
  {
    id: "storm",
    name: "Storm Gym",
    type: "Flying",
    leader: "Aeris",
    badge: "Tempest Badge",
    description: "A sky-platform championship test built for the fastest trainers.",
    theme: "storm",
    accent: "#8fd7ff",
    background: "/battle-gym/viridian_gym.png",
    music: "/battle-music/mus_vs_gym_leader.mp3",
    rewardCoins: 1000000,
    rewardXp: 40000,
    unlockAfter: "fairy",
    team: [
      { name: "staraptor", pokedexId: 398, level: 120, types: ["normal", "flying"], maxHp: 560, attack: 300, defense: 240, speed: 150, moves: [{ name: "Hurricane", type: "flying", power: 110, accuracy: 100, pp: 20 }, { name: "Brave Bird", type: "flying", power: 100, accuracy: 100, pp: 20 }] },
      { name: "noivern", pokedexId: 715, level: 121, types: ["flying", "dragon"], maxHp: 580, attack: 320, defense: 220, speed: 175, moves: [{ name: "Hurricane", type: "flying", power: 110, accuracy: 100, pp: 20 }, { name: "Brave Bird", type: "flying", power: 100, accuracy: 100, pp: 20 }] },
      { name: "corviknight", pokedexId: 823, level: 122, types: ["flying", "steel"], maxHp: 700, attack: 360, defense: 400, speed: 100, moves: [{ name: "Hurricane", type: "flying", power: 110, accuracy: 100, pp: 20 }, { name: "Brave Bird", type: "flying", power: 100, accuracy: 100, pp: 20 }] },
      { name: "pelipper", pokedexId: 279, level: 123, types: ["water", "flying"], maxHp: 620, attack: 350, defense: 260, speed: 110, moves: [{ name: "Hurricane", type: "flying", power: 110, accuracy: 100, pp: 20 }, { name: "Brave Bird", type: "flying", power: 100, accuracy: 100, pp: 20 }] },
      { name: "talonflame", pokedexId: 663, level: 124, types: ["fire", "flying"], maxHp: 650, attack: 330, defense: 250, speed: 185, moves: [{ name: "Hurricane", type: "flying", power: 110, accuracy: 100, pp: 20 }, { name: "Brave Bird", type: "flying", power: 100, accuracy: 100, pp: 20 }] },
      { name: "lugia", pokedexId: 249, level: 126, types: ["psychic", "flying"], maxHp: 980, attack: 500, defense: 480, speed: 170, moves: [{ name: "Hurricane", type: "flying", power: 110, accuracy: 100, pp: 20 }, { name: "Brave Bird", type: "flying", power: 100, accuracy: 100, pp: 20 }] },
    ],
  },
  {
    id: "astral",
    name: "Astral Gym",
    type: "Psychic",
    leader: "Oracle Nyx",
    badge: "Astral Badge",
    description: "A mind-bending observatory where prediction beats raw power.",
    theme: "astral",
    accent: "#c084fc",
    background: "/battle-gym/viridian_gym.png",
    music: "/battle-music/mus_vs_gym_leader.mp3",
    rewardCoins: 1200000,
    rewardXp: 48000,
    unlockAfter: "storm",
    team: [
      { name: "Alakazam", pokedexId: 65, level: 98, types: ["psychic"], maxHp: 820, attack: 520, defense: 430, speed: 260, moves: [{ name: "Psychic Burst", type: "psychic", power: 120, accuracy: 100, pp: 10 }, { name: "Elder Strike", type: "psychic", power: 140, accuracy: 90, pp: 5 }] },
      { name: "Lunala", pokedexId: 792, level: 100, types: ["psychic"], maxHp: 980, attack: 560, defense: 470, speed: 220, moves: [{ name: "Psychic Burst", type: "psychic", power: 120, accuracy: 100, pp: 10 }, { name: "Elder Strike", type: "psychic", power: 140, accuracy: 90, pp: 5 }] },
      { name: "Alakazam", pokedexId: 65, level: 101, types: ["psychic"], maxHp: 900, attack: 580, defense: 500, speed: 280, moves: [{ name: "Psychic Burst", type: "psychic", power: 120, accuracy: 100, pp: 10 }, { name: "Elder Strike", type: "psychic", power: 140, accuracy: 90, pp: 5 }] },
      { name: "Reuniclus", pokedexId: 579, level: 102, types: ["psychic"], maxHp: 940, attack: 590, defense: 520, speed: 130, moves: [{ name: "Psychic Burst", type: "psychic", power: 120, accuracy: 100, pp: 10 }, { name: "Elder Strike", type: "psychic", power: 140, accuracy: 90, pp: 5 }] },
      { name: "Mesprit", pokedexId: 481, level: 104, types: ["psychic"], maxHp: 1000, attack: 620, defense: 550, speed: 240, moves: [{ name: "Psychic Burst", type: "psychic", power: 120, accuracy: 100, pp: 10 }, { name: "Elder Strike", type: "psychic", power: 140, accuracy: 90, pp: 5 }] },
      { name: "Arceus", pokedexId: 493, level: 108, types: ["psychic"], maxHp: 1300, attack: 720, defense: 650, speed: 300, moves: [{ name: "Psychic Burst", type: "psychic", power: 120, accuracy: 100, pp: 10 }, { name: "Elder Strike", type: "psychic", power: 140, accuracy: 90, pp: 5 }] },
    ],
  },
  {
    id: "void",
    name: "Void Gym",
    type: "Dark",
    leader: "Noctra",
    badge: "Eclipse Badge",
    description: "A lightless arena where ruthless dark teams punish every mistake.",
    theme: "void",
    accent: "#64748b",
    background: "/battle-gym/viridian_gym.png",
    music: "/battle-music/mus_vs_gym_leader.mp3",
    rewardCoins: 1450000,
    rewardXp: 56000,
    unlockAfter: "astral",
    team: [
      { name: "Absol", pokedexId: 359, level: 106, types: ["dark"], maxHp: 880, attack: 540, defense: 420, speed: 280, moves: [{ name: "Dark Burst", type: "dark", power: 120, accuracy: 100, pp: 10 }, { name: "Elder Strike", type: "dark", power: 140, accuracy: 90, pp: 5 }] },
      { name: "Zoroark", pokedexId: 571, level: 108, types: ["dark"], maxHp: 900, attack: 560, defense: 420, speed: 300, moves: [{ name: "Dark Burst", type: "dark", power: 120, accuracy: 100, pp: 10 }, { name: "Elder Strike", type: "dark", power: 140, accuracy: 90, pp: 5 }] },
      { name: "Hydreigon", pokedexId: 635, level: 110, types: ["dark"], maxHp: 1100, attack: 680, defense: 560, speed: 250, moves: [{ name: "Dark Burst", type: "dark", power: 120, accuracy: 100, pp: 10 }, { name: "Elder Strike", type: "dark", power: 140, accuracy: 90, pp: 5 }] },
      { name: "Yveltal", pokedexId: 717, level: 112, types: ["dark"], maxHp: 1250, attack: 700, defense: 600, speed: 270, moves: [{ name: "Dark Burst", type: "dark", power: 120, accuracy: 100, pp: 10 }, { name: "Elder Strike", type: "dark", power: 140, accuracy: 90, pp: 5 }] },
      { name: "Darkrai", pokedexId: 491, level: 114, types: ["dark"], maxHp: 1300, attack: 760, defense: 640, speed: 290, moves: [{ name: "Dark Burst", type: "dark", power: 120, accuracy: 100, pp: 10 }, { name: "Elder Strike", type: "dark", power: 140, accuracy: 90, pp: 5 }] },
      { name: "Tyranitar", pokedexId: 248, level: 116, types: ["dark"], maxHp: 1400, attack: 820, defense: 700, speed: 220, moves: [{ name: "Dark Burst", type: "dark", power: 120, accuracy: 100, pp: 10 }, { name: "Elder Strike", type: "dark", power: 140, accuracy: 90, pp: 5 }] },
    ],
  },
  {
    id: "dragon-elder",
    name: "Elder Dragon Gym",
    type: "Dragon",
    leader: "Elder Drakon",
    badge: "Wyrm Crown",
    description: "The final dragon trial: ancient powers, legendary speed, and no second chances.",
    theme: "dragon-elder",
    accent: "#fb7185",
    background: "/battle-gym/viridian_gym.png",
    music: "/battle-music/mus_vs_gym_leader.mp3",
    rewardCoins: 1800000,
    rewardXp: 70000,
    unlockAfter: "void",
    team: [
      { name: "Garchomp", pokedexId: 445, level: 118, types: ["dragon"], maxHp: 1250, attack: 760, defense: 680, speed: 330, moves: [{ name: "Dragon Burst", type: "dragon", power: 120, accuracy: 100, pp: 10 }, { name: "Elder Strike", type: "dragon", power: 140, accuracy: 90, pp: 5 }] },
      { name: "Salamence", pokedexId: 373, level: 120, types: ["dragon"], maxHp: 1280, attack: 780, defense: 650, speed: 340, moves: [{ name: "Dragon Burst", type: "dragon", power: 120, accuracy: 100, pp: 10 }, { name: "Elder Strike", type: "dragon", power: 140, accuracy: 90, pp: 5 }] },
      { name: "Haxorus", pokedexId: 612, level: 122, types: ["dragon"], maxHp: 1300, attack: 820, defense: 650, speed: 320, moves: [{ name: "Dragon Burst", type: "dragon", power: 120, accuracy: 100, pp: 10 }, { name: "Elder Strike", type: "dragon", power: 140, accuracy: 90, pp: 5 }] },
      { name: "Rayquaza", pokedexId: 384, level: 125, types: ["dragon"], maxHp: 1600, attack: 900, defense: 820, speed: 380, moves: [{ name: "Dragon Burst", type: "dragon", power: 120, accuracy: 100, pp: 10 }, { name: "Elder Strike", type: "dragon", power: 140, accuracy: 90, pp: 5 }] },
      { name: "Reshiram", pokedexId: 643, level: 128, types: ["dragon"], maxHp: 1700, attack: 960, defense: 850, speed: 350, moves: [{ name: "Dragon Burst", type: "dragon", power: 120, accuracy: 100, pp: 10 }, { name: "Elder Strike", type: "dragon", power: 140, accuracy: 90, pp: 5 }] },
      { name: "Baxcalibur", pokedexId: 998, level: 130, types: ["dragon"], maxHp: 1550, attack: 940, defense: 800, speed: 300, moves: [{ name: "Dragon Burst", type: "dragon", power: 120, accuracy: 100, pp: 10 }, { name: "Elder Strike", type: "dragon", power: 140, accuracy: 90, pp: 5 }] },
    ],
  },
];

export function gymById(id) {
  return GYMS.find((gym) => gym.id === String(id).toLowerCase()) || null;
}

export function gymBadgeId(id) {
  return `${id}-badge`;
}
