export const GYMS = [
  {
    id: "tide",
    name: "Tide Gym",
    type: "Water",
    leader: "Mira",
    badge: "Tide Badge",
    description: "A rain-soaked arena where timing beats raw power.",
    theme: "tide",
    accent: "#50d7ff",
    background: "/battle-gym/tide.webp",
    music: "/battle-music/tide.mp3",
    rewardCoins: 25000,
    rewardXp: 1200,
    team: [
      { name: "swampert", pokedexId: 260, level: 28, types: ["water", "ground"], maxHp: 180, attack: 92, defense: 88, speed: 65, moves: [{ name: "Water Pulse", type: "water", power: 60, accuracy: 100, pp: 20 }, { name: "Mud Shot", type: "ground", power: 55, accuracy: 100, pp: 20 }] },
      { name: "gyarados", pokedexId: 130, level: 30, types: ["water", "flying"], maxHp: 195, attack: 105, defense: 82, speed: 81, moves: [{ name: "Aqua Tail", type: "water", power: 90, accuracy: 100, pp: 20 }, { name: "Bite", type: "dark", power: 60, accuracy: 100, pp: 20 }] },
      { name: "lapras", pokedexId: 131, level: 31, types: ["water", "ice"], maxHp: 210, attack: 96, defense: 90, speed: 60, moves: [{ name: "Ice Beam", type: "ice", power: 90, accuracy: 100, pp: 20 }, { name: "Water Pulse", type: "water", power: 60, accuracy: 100, pp: 20 }] },
      { name: "kingdra", pokedexId: 230, level: 32, types: ["water", "dragon"], maxHp: 205, attack: 110, defense: 98, speed: 85, moves: [{ name: "Dragon Pulse", type: "dragon", power: 85, accuracy: 100, pp: 20 }, { name: "Brine", type: "water", power: 65, accuracy: 100, pp: 20 }] },
      { name: "milotic", pokedexId: 350, level: 33, types: ["water"], maxHp: 225, attack: 102, defense: 105, speed: 86, moves: [{ name: "Surf", type: "water", power: 90, accuracy: 100, pp: 20 }, { name: "Ice Beam", type: "ice", power: 90, accuracy: 100, pp: 20 }] },
      { name: "greninja", pokedexId: 658, level: 35, types: ["water", "dark"], maxHp: 215, attack: 120, defense: 86, speed: 122, moves: [{ name: "Water Shuriken", type: "water", power: 75, accuracy: 100, pp: 20 }, { name: "Night Slash", type: "dark", power: 70, accuracy: 100, pp: 20 }] },
    ],
  },
  {
    id: "ember",
    name: "Ember Gym",
    type: "Fire",
    leader: "Kaida",
    badge: "Ember Badge",
    description: "A volcanic ring where every turn burns brighter.",
    theme: "ember",
    accent: "#ff886c",
    background: "/battle-gym/ember.webp",
    music: "/battle-music/ember.mp3",
    rewardCoins: 35000,
    rewardXp: 1800,
    unlockAfter: "tide",
    team: [
      { name: "arcanine", pokedexId: 59, level: 34, types: ["fire"], maxHp: 205, attack: 112, defense: 85, speed: 95, moves: [{ name: "Flame Wheel", type: "fire", power: 75, accuracy: 100, pp: 20 }, { name: "Bite", type: "dark", power: 60, accuracy: 100, pp: 20 }] },
      { name: "charizard", pokedexId: 6, level: 36, types: ["fire", "flying"], maxHp: 220, attack: 118, defense: 90, speed: 105, moves: [{ name: "Flamethrower", type: "fire", power: 90, accuracy: 100, pp: 20 }, { name: "Dragon Claw", type: "dragon", power: 80, accuracy: 100, pp: 20 }] },
      { name: "ninetales", pokedexId: 38, level: 35, types: ["fire"], maxHp: 190, attack: 104, defense: 86, speed: 100, moves: [{ name: "Fire Blast", type: "fire", power: 100, accuracy: 100, pp: 20 }, { name: "Confuse Ray", type: "ghost", power: 0, accuracy: 100, pp: 20 }] },
      { name: "volcarona", pokedexId: 637, level: 37, types: ["bug", "fire"], maxHp: 215, attack: 122, defense: 84, speed: 100, moves: [{ name: "Bug Buzz", type: "bug", power: 90, accuracy: 100, pp: 20 }, { name: "Flamethrower", type: "fire", power: 90, accuracy: 100, pp: 20 }] },
      { name: "talonflame", pokedexId: 663, level: 38, types: ["fire", "flying"], maxHp: 200, attack: 126, defense: 78, speed: 126, moves: [{ name: "Brave Bird", type: "flying", power: 100, accuracy: 100, pp: 20 }, { name: "Flame Charge", type: "fire", power: 50, accuracy: 100, pp: 20 }] },
      { name: "blaziken", pokedexId: 257, level: 40, types: ["fire", "fighting"], maxHp: 230, attack: 135, defense: 92, speed: 95, moves: [{ name: "Blaze Kick", type: "fire", power: 85, accuracy: 100, pp: 20 }, { name: "Brick Break", type: "fighting", power: 75, accuracy: 100, pp: 20 }] },
    ],
  },
  {
    id: "voltage",
    name: "Voltage Gym",
    type: "Electric",
    leader: "Volt",
    badge: "Voltage Badge",
    description: "Neon rails, charged platforms, and lightning-fast turns.",
    theme: "voltage",
    accent: "#ffe66d",
    background: "/battle-gym/voltage.webp",
    music: "/battle-music/voltage.mp3",
    rewardCoins: 50000,
    rewardXp: 2400,
    unlockAfter: "ember",
    team: [
      { name: "luxray", pokedexId: 405, level: 40, types: ["electric"], maxHp: 230, attack: 125, defense: 95, speed: 88, moves: [{ name: "Spark", type: "electric", power: 65, accuracy: 100, pp: 20 }, { name: "Crunch", type: "dark", power: 80, accuracy: 100, pp: 20 }] },
      { name: "zeraora", pokedexId: 807, level: 42, types: ["electric"], maxHp: 245, attack: 135, defense: 92, speed: 125, moves: [{ name: "Thunder Punch", type: "electric", power: 75, accuracy: 100, pp: 20 }, { name: "Slash", type: "normal", power: 70, accuracy: 100, pp: 20 }] },
      { name: "ampharos", pokedexId: 181, level: 41, types: ["electric"], maxHp: 240, attack: 118, defense: 100, speed: 72, moves: [{ name: "Thunderbolt", type: "electric", power: 90, accuracy: 100, pp: 20 }, { name: "Dragon Pulse", type: "dragon", power: 85, accuracy: 100, pp: 20 }] },
      { name: "magnezone", pokedexId: 462, level: 42, types: ["electric", "steel"], maxHp: 250, attack: 125, defense: 128, speed: 60, moves: [{ name: "Flash Cannon", type: "steel", power: 80, accuracy: 100, pp: 20 }, { name: "Thunderbolt", type: "electric", power: 90, accuracy: 100, pp: 20 }] },
      { name: "rotom", pokedexId: 479, level: 43, types: ["electric", "ghost"], maxHp: 220, attack: 118, defense: 100, speed: 110, moves: [{ name: "Shock Wave", type: "electric", power: 60, accuracy: 100, pp: 20 }, { name: "Shadow Ball", type: "ghost", power: 80, accuracy: 100, pp: 20 }] },
      { name: "electivire", pokedexId: 466, level: 44, types: ["electric"], maxHp: 255, attack: 140, defense: 94, speed: 100, moves: [{ name: "Thunder Punch", type: "electric", power: 75, accuracy: 100, pp: 20 }, { name: "Brick Break", type: "fighting", power: 75, accuracy: 100, pp: 20 }] },
    ],
  },
  {
    id: "shadow",
    name: "Shadow Gym",
    type: "Ghost",
    leader: "Noctis",
    badge: "Shadow Badge",
    description: "A moonlit ruin filled with illusions and spectral wind.",
    theme: "shadow",
    accent: "#c59bff",
    background: "/battle-gym/shadow.webp",
    music: "/battle-music/shadow.mp3",
    rewardCoins: 75000,
    rewardXp: 3200,
    unlockAfter: "voltage",
    team: [
      { name: "gengar", pokedexId: 94, level: 46, types: ["ghost", "poison"], maxHp: 235, attack: 120, defense: 85, speed: 118, moves: [{ name: "Shadow Ball", type: "ghost", power: 80, accuracy: 100, pp: 20 }, { name: "Sludge Bomb", type: "poison", power: 90, accuracy: 100, pp: 20 }] },
      { name: "dragapult", pokedexId: 887, level: 48, types: ["dragon", "ghost"], maxHp: 250, attack: 140, defense: 92, speed: 142, moves: [{ name: "Dragon Darts", type: "dragon", power: 90, accuracy: 100, pp: 20 }, { name: "Phantom Force", type: "ghost", power: 100, accuracy: 100, pp: 20 }] },
      { name: "mimikyu", pokedexId: 778, level: 47, types: ["ghost", "fairy"], maxHp: 220, attack: 126, defense: 98, speed: 105, moves: [{ name: "Shadow Claw", type: "ghost", power: 70, accuracy: 100, pp: 20 }, { name: "Play Rough", type: "fairy", power: 90, accuracy: 100, pp: 20 }] },
      { name: "chandelure", pokedexId: 609, level: 48, types: ["ghost", "fire"], maxHp: 235, attack: 135, defense: 92, speed: 100, moves: [{ name: "Shadow Ball", type: "ghost", power: 80, accuracy: 100, pp: 20 }, { name: "Flamethrower", type: "fire", power: 90, accuracy: 100, pp: 20 }] },
      { name: "aegislash", pokedexId: 681, level: 49, types: ["steel", "ghost"], maxHp: 255, attack: 145, defense: 135, speed: 60, moves: [{ name: "Iron Head", type: "steel", power: 80, accuracy: 100, pp: 20 }, { name: "Shadow Sneak", type: "ghost", power: 40, accuracy: 100, pp: 20 }] },
      { name: "giratina", pokedexId: 487, level: 52, types: ["ghost", "dragon"], maxHp: 290, attack: 152, defense: 140, speed: 90, moves: [{ name: "Shadow Force", type: "ghost", power: 100, accuracy: 100, pp: 20 }, { name: "Dragon Claw", type: "dragon", power: 80, accuracy: 100, pp: 20 }] },
    ],
  },
];

export function gymById(id) {
  return GYMS.find((gym) => gym.id === String(id).toLowerCase()) || null;
}

export function gymBadgeId(id) {
  return `${id}-badge`;
}
