/**
 * Local anime quiz bank.
 *
 * Keep every question text unique. The quiz engine shuffles this bank for each
 * session and only reshuffles after the entire bank has been used.
 */
export const ANIME_QUIZ_QUESTIONS = [
  { question: "Who is the captain of the Straw Hat Pirates?", options: ["Monkey D. Luffy", "Roronoa Zoro", "Shanks", "Portgas D. Ace"], answer: "Monkey D. Luffy" },
  { question: "What is the legendary treasure sought by the Straw Hat Pirates?", options: ["One Piece", "All Blue", "Pluton", "Laugh Tale"], answer: "One Piece" },
  { question: "Who is the swordsman of the Straw Hat crew?", options: ["Roronoa Zoro", "Dracule Mihawk", "Trafalgar Law", "Killer"], answer: "Roronoa Zoro" },
  { question: "Who is the navigator of the Straw Hat Pirates?", options: ["Nami", "Nico Robin", "Vivi", "Boa Hancock"], answer: "Nami" },
  { question: "Who is the sniper of the Straw Hat crew?", options: ["Usopp", "Franky", "Sanji", "Brook"], answer: "Usopp" },
  { question: "Who is the chef of the Straw Hat Pirates?", options: ["Sanji", "Zeff", "Vinsmoke Judge", "Brook"], answer: "Sanji" },
  { question: "Who is the doctor of the Straw Hat crew?", options: ["Tony Tony Chopper", "Hiriluk", "Marco", "Law"], answer: "Tony Tony Chopper" },
  { question: "Who is the archaeologist of the Straw Hat Pirates?", options: ["Nico Robin", "Nami", "Perona", "Reiju"], answer: "Nico Robin" },
  { question: "What is the name of the Straw Hat crew's current ship?", options: ["Thousand Sunny", "Going Merry", "Red Force", "Polar Tang"], answer: "Thousand Sunny" },
  { question: "What was the Straw Hat crew's first ship?", options: ["Going Merry", "Thousand Sunny", "Oro Jackson", "Moby Dick"], answer: "Going Merry" },
  { question: "Which pirate is known as the Red-Haired Shanks?", options: ["Shanks", "Buggy", "Rayleigh", "Teach"], answer: "Shanks" },
  { question: "What is the name of the sea route where the Grand Line lies?", options: ["The Grand Line", "The Calm Belt", "The Red Line", "The North Blue"], answer: "The Grand Line" },
  { question: "Which attack form is associated with Luffy's Fourth Gear?", options: ["Boundman", "Ashura", "Diable Jambe", "Room"], answer: "Boundman" },
  { question: "What sword-fighting style does Zoro use?", options: ["Three Sword Style", "One Sword Style", "Six Sword Style", "Black Leg Style"], answer: "Three Sword Style" },
  { question: "Who leads the Revolutionary Army in One Piece?", options: ["Monkey D. Dragon", "Sabo", "Monkey D. Garp", "Ivankov"], answer: "Monkey D. Dragon" },
  { question: "Which pirate is famous for using the Yami Yami no Mi?", options: ["Marshall D. Teach", "Shanks", "Crocodile", "Doflamingo"], answer: "Marshall D. Teach" },
  { question: "Who is the king of Fish-Man Island?", options: ["King Neptune", "Fisher Tiger", "Jinbe", "Hody Jones"], answer: "King Neptune" },
  { question: "Who was the former ruler of Dressrosa?", options: ["Donquixote Doflamingo", "Cavendish", "Kyros", "King Riku"], answer: "Donquixote Doflamingo" },
  { question: "Who is the legendary samurai of Wano known as the Daimyo of Kuri?", options: ["Kozuki Oden", "Momonosuke", "Kinemon", "Denjiro"], answer: "Kozuki Oden" },
  { question: "Which CP9 member is known for his leopard transformation?", options: ["Rob Lucci", "Kaku", "Jabra", "Blueno"], answer: "Rob Lucci" },
  { question: "What was Luffy's first bounty?", options: ["30,000,000 Berries", "15,000,000 Berries", "100,000,000 Berries", "5,000,000 Berries"], answer: "30,000,000 Berries" },
  { question: "Who is the musician of the Straw Hat Pirates?", options: ["Brook", "Franky", "Usopp", "Cavendish"], answer: "Brook" },
  { question: "Who is the shipwright of the Straw Hat crew?", options: ["Franky", "Iceburg", "Tom", "Paulie"], answer: "Franky" },
  { question: "Who is the helmsman of the Straw Hat Pirates?", options: ["Jinbe", "Franky", "Nami", "Arlong"], answer: "Jinbe" },
  { question: "What island is ruled by Boa Hancock?", options: ["Amazon Lily", "Whole Cake Island", "Dawn Island", "Drum Island"], answer: "Amazon Lily" },
  { question: "What is the name of the sky island visited by the Straw Hats?", options: ["Skypiea", "Zou", "Elbaf", "Water 7"], answer: "Skypiea" },
  { question: "Which Straw Hat can read the ancient Poneglyphs?", options: ["Nico Robin", "Nami", "Chopper", "Franky"], answer: "Nico Robin" },
  { question: "What is the name of the giant whale at Reverse Mountain?", options: ["Laboon", "Surume", "Zunesha", "Sea King"], answer: "Laboon" },
  { question: "Who is the father of Monkey D. Luffy?", options: ["Monkey D. Dragon", "Monkey D. Garp", "Gol D. Roger", "Silvers Rayleigh"], answer: "Monkey D. Dragon" },
  { question: "Which character is called the Dark King?", options: ["Silvers Rayleigh", "Gol D. Roger", "Shanks", "Mihawk"], answer: "Silvers Rayleigh" },
  { question: "Who is the main character of Naruto?", options: ["Naruto Uzumaki", "Sasuke Uchiha", "Kakashi Hatake", "Shikamaru Nara"], answer: "Naruto Uzumaki" },
  { question: "Which village is Naruto from?", options: ["Hidden Leaf Village", "Hidden Sand Village", "Hidden Mist Village", "Hidden Cloud Village"], answer: "Hidden Leaf Village" },
  { question: "What is the name of the Nine-Tailed Fox inside Naruto?", options: ["Kurama", "Shukaku", "Gyuki", "Matatabi"], answer: "Kurama" },
  { question: "Who is Naruto's main rival?", options: ["Sasuke Uchiha", "Neji Hyuga", "Gaara", "Rock Lee"], answer: "Sasuke Uchiha" },
  { question: "Who was the leader of Team 7?", options: ["Kakashi Hatake", "Jiraiya", "Might Guy", "Iruka Umino"], answer: "Kakashi Hatake" },
  { question: "Which eye technique belongs to the Uchiha clan?", options: ["Sharingan", "Byakugan", "Rinnegan", "Jogan"], answer: "Sharingan" },
  { question: "Which eye technique is associated with the Hyuga clan?", options: ["Byakugan", "Sharingan", "Rinnegan", "Ketsuryugan"], answer: "Byakugan" },
  { question: "What is the real name of Pain?", options: ["Nagato", "Yahiko", "Obito", "Madara"], answer: "Nagato" },
  { question: "Who becomes the Seventh Hokage?", options: ["Naruto Uzumaki", "Kakashi Hatake", "Sasuke Uchiha", "Shikamaru Nara"], answer: "Naruto Uzumaki" },
  { question: "Who is the Fifth Hokage?", options: ["Tsunade", "Tsunade", "Mei Terumi", "Kushina Uzumaki"], answer: "Tsunade" },
  { question: "Who was the First Hokage?", options: ["Hashirama Senju", "Tobirama Senju", "Hiruzen Sarutobi", "Minato Namikaze"], answer: "Hashirama Senju" },
  { question: "Who is Itachi Uchiha's younger brother?", options: ["Sasuke Uchiha", "Shisui Uchiha", "Madara Uchiha", "Obito Uchiha"], answer: "Sasuke Uchiha" },
  { question: "Which village is Gaara the Kazekage of?", options: ["Hidden Sand Village", "Hidden Leaf Village", "Hidden Stone Village", "Hidden Cloud Village"], answer: "Hidden Sand Village" },
  { question: "What giant toad can Naruto summon?", options: ["Gamabunta", "Manda", "Katsuyu", "Aoda"], answer: "Gamabunta" },
  { question: "How many tails does Kurama have?", options: ["Nine", "Eight", "Seven", "Ten"], answer: "Nine" },
  { question: "Where are the Chunin Exams held?", options: ["Konohagakure", "Sunagakure", "Kirigakure", "Iwagakure"], answer: "Konohagakure" },
  { question: "Who is Rock Lee's teacher?", options: ["Might Guy", "Kakashi Hatake", "Asuma Sarutobi", "Jiraiya"], answer: "Might Guy" },
  { question: "What is the name of the mountain where Naruto learns Sage Mode?", options: ["Mount Myoboku", "Mount Hakurei", "Mount Everest", "Mount Koya"], answer: "Mount Myoboku" },
  { question: "Who created the Rasengan?", options: ["Minato Namikaze", "Jiraiya", "Kakashi Hatake", "Naruto Uzumaki"], answer: "Minato Namikaze" },
  { question: "Which character is known as the Copy Ninja?", options: ["Kakashi Hatake", "Sasuke Uchiha", "Itachi Uchiha", "Kabuto Yakushi"], answer: "Kakashi Hatake" },
  { question: "What does Deidara use for his explosive art?", options: ["Explosive Clay", "Paper Bombs", "Fire Release", "Puppets"], answer: "Explosive Clay" },
  { question: "Which jutsu is Shikamaru best known for?", options: ["Shadow Possession Jutsu", "Rasengan", "Chidori", "Mind Transfer Jutsu"], answer: "Shadow Possession Jutsu" },
  { question: "Which clan does Neji belong to?", options: ["Hyuga", "Uchiha", "Nara", "Aburame"], answer: "Hyuga" },
  { question: "Who is the final major antagonist of Naruto Shippuden?", options: ["Kaguya Otsutsuki", "Madara Uchiha", "Obito Uchiha", "Black Zetsu"], answer: "Kaguya Otsutsuki" },
  { question: "What is Naruto's mother's name?", options: ["Kushina Uzumaki", "Mikoto Uchiha", "Tsunade", "Mito Uzumaki"], answer: "Kushina Uzumaki" },
  { question: "Who is the main hero of Dragon Ball?", options: ["Son Goku", "Vegeta", "Gohan", "Trunks"], answer: "Son Goku" },
  { question: "What race is Goku?", options: ["Saiyan", "Namekian", "Android", "Human"], answer: "Saiyan" },
  { question: "Who is Goku's proud Saiyan rival?", options: ["Vegeta", "Raditz", "Nappa", "Broly"], answer: "Vegeta" },
  { question: "Which dragon is summoned by the Earth Dragon Balls?", options: ["Shenron", "Porunga", "Super Shenron", "Eis Shenron"], answer: "Shenron" },
  { question: "What is Goku's famous energy attack?", options: ["Kamehameha", "Final Flash", "Galick Gun", "Special Beam Cannon"], answer: "Kamehameha" },
  { question: "Which planet is central to the Frieza Saga?", options: ["Namek", "Earth", "Vegeta", "Yardrat"], answer: "Namek" },
  { question: "Who is the fusion of Goten and Trunks?", options: ["Gotenks", "Vegito", "Gogeta", "Kefla"], answer: "Gotenks" },
  { question: "Who first achieves Super Saiyan in the original Dragon Ball Z story?", options: ["Goku", "Vegeta", "Gohan", "Future Trunks"], answer: "Goku" },
  { question: "What race is Piccolo?", options: ["Namekian", "Saiyan", "Human", "Frieza Race"], answer: "Namekian" },
  { question: "Who is Gohan's father?", options: ["Goku", "Vegeta", "Piccolo", "Bardock"], answer: "Goku" },
  { question: "Which Android is Android 18's twin brother?", options: ["Android 17", "Android 16", "Cell", "Android 19"], answer: "Android 17" },
  { question: "What tournament is held during the Cell Saga?", options: ["Cell Games", "World Martial Arts Tournament", "Tournament of Power", "Other World Tournament"], answer: "Cell Games" },
  { question: "Who is the God of Destruction for Universe 7?", options: ["Beerus", "Whis", "Champa", "Grand Priest"], answer: "Beerus" },
  { question: "What is Whis's role?", options: ["Angel attendant", "God of Destruction", "Supreme Kai", "Galactic Patrolman"], answer: "Angel attendant" },
  { question: "What is the name of the survival battle in Dragon Ball Super?", options: ["Tournament of Power", "Cell Games", "World Tournament", "Battle of Gods"], answer: "Tournament of Power" },
  { question: "Who invented the Dragon Radar?", options: ["Bulma", "Dr. Brief", "Launch", "Chi-Chi"], answer: "Bulma" },
  { question: "Who trained Goku as a child on Earth?", options: ["Master Roshi", "King Kai", "Kami", "Mr. Popo"], answer: "Master Roshi" },
  { question: "Who is Goku's teacher in Other World?", options: ["King Kai", "Master Roshi", "Whis", "Supreme Kai"], answer: "King Kai" },
  { question: "Who is the time-traveling son of Vegeta?", options: ["Future Trunks", "Goten", "Bulla", "Cabba"], answer: "Future Trunks" },
  { question: "Which villain is known as Majin Buu?", options: ["Majin Buu", "Frieza", "Cell", "Kid Goku"], answer: "Majin Buu" },
  { question: "Who is the main protagonist of Bleach?", options: ["Ichigo Kurosaki", "Uryu Ishida", "Renji Abarai", "Kisuke Urahara"], answer: "Ichigo Kurosaki" },
  { question: "What is the name of Ichigo's Zanpakuto?", options: ["Zangetsu", "Senbonzakura", "Sode no Shirayuki", "Hyorinmaru"], answer: "Zangetsu" },
  { question: "Where do the Soul Reapers primarily live?", options: ["Soul Society", "Hueco Mundo", "Karakura Town", "Wandenreich"], answer: "Soul Society" },
  { question: "Who is the Soul Reaper who gives Ichigo his powers?", options: ["Rukia Kuchiki", "Yoruichi Shihoin", "Rangiku Matsumoto", "Soi Fon"], answer: "Rukia Kuchiki" },
  { question: "What race is Uryu Ishida?", options: ["Quincy", "Soul Reaper", "Arrancar", "Fullbringer"], answer: "Quincy" },
  { question: "Who is the main villain of the Soul Society and Arrancar arcs?", options: ["Sosuke Aizen", "Yhwach", "Gin Ichimaru", "Ulquiorra"], answer: "Sosuke Aizen" },
  { question: "Who leads Squad 11 for much of Bleach?", options: ["Kenpachi Zaraki", "Byakuya Kuchiki", "Toshiro Hitsugaya", "Shunsui Kyoraku"], answer: "Kenpachi Zaraki" },
  { question: "What is Byakuya Kuchiki's family name?", options: ["Kuchiki", "Shihouin", "Urahara", "Kurosaki"], answer: "Kuchiki" },
  { question: "What is Ichigo's Bankai called?", options: ["Tensa Zangetsu", "Daiguren Hyorinmaru", "Senbonzakura Kageyoshi", "Kannonbiraki Benihime Aratame"], answer: "Tensa Zangetsu" },
  { question: "Which character can heal people with her Shun Shun Rikka?", options: ["Orihime Inoue", "Rukia Kuchiki", "Nemu Kurotsuchi", "Isane Kotetsu"], answer: "Orihime Inoue" },
  { question: "Who is the former owner of the Benihime Zanpakuto?", options: ["Kisuke Urahara", "Shinji Hirako", "Isshin Kurosaki", "Mayuri Kurotsuchi"], answer: "Kisuke Urahara" },
  { question: "Who is known as the Quincy King?", options: ["Yhwach", "Uryu Ishida", "Jugram Haschwalth", "Ryuken Ishida"], answer: "Yhwach" },
  { question: "What is the desert realm of the Hollows called?", options: ["Hueco Mundo", "Soul Society", "Dangai", "Wandenreich"], answer: "Hueco Mundo" },
  { question: "Who is the ruler at the center of Soul Society's balance?", options: ["Soul King", "Central 46", "Genryusai Yamamoto", "Royal Guard"], answer: "Soul King" },
  { question: "Who is the protagonist of Demon Slayer?", options: ["Tanjiro Kamado", "Zenitsu Agatsuma", "Inosuke Hashibira", "Giyu Tomioka"], answer: "Tanjiro Kamado" },
  { question: "Who is Tanjiro's demon sister?", options: ["Nezuko Kamado", "Kanao Tsuyuri", "Mitsuri Kanroji", "Aoi Kanzaki"], answer: "Nezuko Kamado" },
  { question: "Which breathing style does Tanjiro first learn?", options: ["Water Breathing", "Flame Breathing", "Thunder Breathing", "Wind Breathing"], answer: "Water Breathing" },
  { question: "Who is the Flame Hashira?", options: ["Kyojuro Rengoku", "Shinjuro Rengoku", "Tengen Uzui", "Muichiro Tokito"], answer: "Kyojuro Rengoku" },
  { question: "Who is the Sound Hashira?", options: ["Tengen Uzui", "Kyojuro Rengoku", "Sanemi Shinazugawa", "Obanai Iguro"], answer: "Tengen Uzui" },
  { question: "Who is Upper Rank One among the demons?", options: ["Kokushibo", "Akaza", "Doma", "Gyutaro"], answer: "Kokushibo" },
  { question: "Who is the main demon leader in Demon Slayer?", options: ["Muzan Kibutsuji", "Kokushibo", "Akaza", "Tamayo"], answer: "Muzan Kibutsuji" },
  { question: "What plant is dangerous to demons?", options: ["Wisteria", "Sunflower", "Bamboo", "Lotus"], answer: "Wisteria" },
  { question: "Which Hashira is associated with insects?", options: ["Shinobu Kocho", "Mitsuri Kanroji", "Kanae Kocho", "Kanao Tsuyuri"], answer: "Shinobu Kocho" },
  { question: "Which village is the setting of the Swordsmith Village Arc?", options: ["Swordsmith Village", "Butterfly Mansion", "Asakusa", "Mount Sagiri"], answer: "Swordsmith Village" },
  { question: "Who is the main character of Jujutsu Kaisen?", options: ["Yuji Itadori", "Megumi Fushiguro", "Satoru Gojo", "Yuta Okkotsu"], answer: "Yuji Itadori" },
  { question: "Which curse lives inside Yuji Itadori?", options: ["Ryomen Sukuna", "Mahito", "Jogo", "Hanami"], answer: "Ryomen Sukuna" },
  { question: "Who is known as the strongest modern sorcerer?", options: ["Satoru Gojo", "Suguru Geto", "Yuta Okkotsu", "Kento Nanami"], answer: "Satoru Gojo" },
  { question: "What power source do Jujutsu sorcerers use?", options: ["Cursed Energy", "Chakra", "Nen", "Spiritual Pressure"], answer: "Cursed Energy" },
  { question: "Who uses the Ten Shadows Technique?", options: ["Megumi Fushiguro", "Yuji Itadori", "Nobara Kugisaki", "Toji Fushiguro"], answer: "Megumi Fushiguro" },
  { question: "Who is the hammer-and-nails user in the main trio?", options: ["Nobara Kugisaki", "Maki Zenin", "Mai Zenin", "Kasumi Miwa"], answer: "Nobara Kugisaki" },
  { question: "What is Gojo's Domain Expansion called?", options: ["Unlimited Void", "Malevolent Shrine", "Chimera Shadow Garden", "Self-Embodiment of Perfection"], answer: "Unlimited Void" },
  { question: "Who is Megumi's father?", options: ["Toji Fushiguro", "Naobito Zenin", "Jin Itadori", "Noritoshi Kamo"], answer: "Toji Fushiguro" },
  { question: "Which school does Yuji attend?", options: ["Tokyo Jujutsu High", "Kyoto Jujutsu High", "UA High School", "Jujutsu Academy of Osaka"], answer: "Tokyo Jujutsu High" },
  { question: "Which curse can reshape the soul?", options: ["Mahito", "Jogo", "Dagon", "Hanami"], answer: "Mahito" },
  { question: "Who is the main character of My Hero Academia?", options: ["Izuku Midoriya", "Katsuki Bakugo", "Shoto Todoroki", "Tenya Iida"], answer: "Izuku Midoriya" },
  { question: "What is All Might's Quirk?", options: ["One For All", "All For One", "Muscle Form", "Symbol of Peace"], answer: "One For All" },
  { question: "What is the name of Deku's Quirk?", options: ["One For All", "Full Cowl", "Danger Sense", "Blackwhip"], answer: "One For All" },
  { question: "What is Bakugo's Quirk?", options: ["Explosion", "Combustion", "Blast", "Nitroglycerin"], answer: "Explosion" },
  { question: "What are Shoto Todoroki's two elements?", options: ["Ice and Fire", "Water and Lightning", "Wind and Fire", "Earth and Ice"], answer: "Ice and Fire" },
  { question: "What hero school do the main students attend?", options: ["UA High School", "Shiketsu High School", "Ketsubutsu Academy", "Seiai Academy"], answer: "UA High School" },
  { question: "Who is the number one Pro Hero after All Might?", options: ["Endeavor", "Hawks", "Best Jeanist", "Mirko"], answer: "Endeavor" },
  { question: "Who is the leader of the League of Villains?", options: ["Tomura Shigaraki", "All For One", "Dabi", "Himiko Toga"], answer: "Tomura Shigaraki" },
  { question: "What is Momo Yaoyorozu's Quirk?", options: ["Creation", "Creationism", "Materialize", "Construct"], answer: "Creation" },
  { question: "What is Izuku Midoriya's hero name?", options: ["Deku", "Might Boy", "One For All", "Green Hero"], answer: "Deku" },
];