/**
 * KELIN MD — Group participant event handler
 * Handles:
 *   • Bot added to a group  → "THANKS FOR ADDING ME HERE 💐"
 *   • Member joins a group  → welcome message or welcome card (if enabled)
 *   • Member leaves a group → goodbye message (if enabled)
 *
 * Registered in lib/bot.mjs on the "group-participants.update" Baileys event.
 */
import { groupSettings } from "./groupSettings.js";
import { generateWelcomeCard } from "./davidcyrilAPI.mjs";
import { log } from "./logger.mjs";

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Strip a JID to bare digits: "27628114340:5@s.whatsapp.net" → "27628114340" */
function jidNum(jid = "") {
  return jid.split("@")[0].split(":")[0].replace(/\D/g, "");
}

/** Try to fetch a member's display name, fall back to their number. */
async function getDisplayName(sock, participantJid, groupMeta) {
  const num = jidNum(participantJid);
  try {
    const biz = await sock.getBusinessProfile(participantJid);
    if (biz?.name) return biz.name;
  } catch { /* not a business */ }
  try {
    const p = (groupMeta?.participants || []).find(x => x.id === participantJid);
    if (p?.name) return p.name;
  } catch { /* ignore */ }
  return num;
}

/**
 * Fetch a participant's profile picture URL.
 * Returns null if the picture is not accessible (private or not set).
 */
async function getProfilePicUrl(sock, jid) {
  try {
    return await sock.profilePictureUrl(jid, "image");
  } catch {
    return null;
  }
}

/**
 * Resolve template variables in a custom message.
 * Supports:
 *   @user  → member's number
 *   @group → group name
 *   @count → member count
 *   \n     → paragraph break (literal \n escape in single-line messages)
 */
function applyVars(template, { user, group, count }) {
  return template
    .replace(/@user/g,  `@${user}`)
    .replace(/@group/g, group)
    .replace(/@count/g, String(count))
    .replace(/\\n/g, "\n");   // allow \n as explicit newline escape
}

/** Format the current time in Africa/Lagos timezone. */
function timeStr() {
  return new Date().toLocaleString("en-NG", {
    timeZone:   "Africa/Lagos",
    month:  "2-digit",
    day:    "2-digit",
    year:   "numeric",
    hour:   "2-digit",
    minute: "2-digit",
    hour12: true,
  });
}

// ── Default fallback avatar (generic silhouette) ──────────────────────────────
const FALLBACK_AVATAR = "https://i.imgur.com/8lOv3tB.png";

// ── Default messages ──────────────────────────────────────────────────────────

function defaultWelcome({ num, groupName, memberCount }) {
  return (
`╭━━━〔 👋 *WELCOME!* 〕━━━╮

  🙋 Member : @${num}
  👥 Count  : ${memberCount}
  🕐 Time   : ${timeStr()}

  Welcome to *${groupName}*! 🎉
  We're glad to have you here.

╰━━━━━━━━━━━━━━━━━━━━╯

> _Powered by KELIN MD_ ⚡`
  );
}

function defaultGoodbye({ num, groupName, memberCount }) {
  return (
`👋 *@${num}* has left *${groupName}*.

We'll miss you! Take care 🙏

> _KELIN MD_ ⚡`
  );
}

// ── Welcome card sender ───────────────────────────────────────────────────────

/**
 * Send a welcome card image generated by the David Cyril Canvas API.
 * Falls back to text welcome if the card generation fails.
 */
async function sendWelcomeCard(sock, groupJid, participantJid, {
  num, groupName, memberCount, settings,
}) {
  // Resolve member's profile picture; use fallback if unavailable
  let avatar;
  try {
    avatar = await getProfilePicUrl(sock, participantJid);
  } catch { /* ignore */ }
  if (!avatar) avatar = FALLBACK_AVATAR;

  // Build card texts
  const text1 = `@${num}`;
  const text2 = settings.welcome
    ? applyVars(settings.welcome, { user: num, group: groupName, count: memberCount })
        .replace(/^@\d+\s*/u, "")   // strip leading @number if template starts with it
        .split("\n")[0]              // card supports a single-line subtitle
        .substring(0, 80)
    : `Welcome to ${groupName}! 🎉`;
  const text3 = `Member ${memberCount}`;

  try {
    const cardBuffer = await generateWelcomeCard({
      avatar,
      text1,
      text2,
      text3,
      background: settings.welcomeCardBg || undefined,
    });

    // Send the card image with a mention caption
    await sock.sendMessage(groupJid, {
      image:   cardBuffer,
      caption: `👋 Welcome, @${num}! We're glad to have you in *${groupName}*.`,
      mentions: [participantJid],
    });
    return true;
  } catch (cardErr) {
    log("warn", `Welcome card generation failed: ${cardErr.message} — falling back to text`);
    return false;
  }
}

// ── Main handler ──────────────────────────────────────────────────────────────

/**
 * Call this from bot.mjs on every "group-participants.update" event.
 *
 * @param {object} sock   – Baileys socket
 * @param {object} update – { id, participants, action }
 */
export async function handleGroupParticipants(sock, update) {
  const { id: groupJid, participants, action } = update;

  // Resolve bot's own JID digits once
  const botJid = sock.user?.id || "";
  const botNum = jidNum(botJid);

  // Fetch group metadata once (shared across all participants in this event)
  let groupMeta = null;
  try {
    groupMeta = await sock.groupMetadata(groupJid);
  } catch { /* metadata unavailable */ }

  const groupName = groupMeta?.subject || "the group";
  const memberCount = groupMeta?.participants?.length ?? 0;

  for (const rawParticipant of participants) {
    const participantJid = typeof rawParticipant === "string"
      ? rawParticipant
      : rawParticipant.id || String(rawParticipant);

    const participantNum = jidNum(participantJid);

    // ── BOT was added to the group ──────────────────────────────────────────
    if (action === "add" && participantNum === botNum) {
      try {
        await sock.sendMessage(groupJid, {
          text: "THANKS FOR ADDING ME HERE 💐",
        });
        log("info", `Bot added to group: ${groupJid}`);
      } catch (err) {
        log("error", `Failed to send join greeting: ${err.message}`);
      }
      continue;
    }

    // ── Regular member JOINED ───────────────────────────────────────────────
    if (action === "add") {
      const settings = groupSettings.get(groupJid);
      if (!settings?.welcomeEnabled) continue;

      try {
        const num = participantNum;

        // Card mode: generate an image using the member's PFP
        if (settings.welcomeCard) {
          const sent = await sendWelcomeCard(sock, groupJid, participantJid, {
            num,
            groupName,
            memberCount,
            settings,
          });
          if (sent) continue; // card sent successfully — skip text fallback
        }

        // Text welcome (default, or card fallback)
        let text;
        if (settings.welcome) {
          text = applyVars(settings.welcome, {
            user:  num,
            group: groupName,
            count: memberCount,
          });
        } else {
          text = defaultWelcome({ num, groupName, memberCount });
        }

        await sock.sendMessage(groupJid, {
          text,
          mentions: [participantJid],
        });
      } catch (err) {
        log("error", `Welcome message error: ${err.message}`);
      }
      continue;
    }

    // ── Regular member LEFT / was REMOVED ──────────────────────────────────
    if (action === "remove") {
      const settings = groupSettings.get(groupJid);
      if (!settings?.goodbyeEnabled) continue;

      try {
        const num = participantNum;

        let text;
        if (settings.goodbye) {
          text = applyVars(settings.goodbye, {
            user:  num,
            group: groupName,
            count: memberCount,
          });
        } else {
          text = defaultGoodbye({ num, groupName, memberCount });
        }

        await sock.sendMessage(groupJid, {
          text,
          mentions: [participantJid],
        });
      } catch (err) {
        log("error", `Goodbye message error: ${err.message}`);
      }
    }
  }
}
