// lib/items.js
// Master item catalogue — used by nshop, ninventory, and nbattle.
//
// types:
//   consumable  → usable outside OR inside battle (costs a turn); effect: { hp, chakra }
//   battle      → usable only in battle; deals direct damage; needs: damage
//   weapon      → passive stat boost (attack); not directly usable mid-battle
//   armor       → passive stat boost (defense); not directly usable mid-battle
//   special     → one-time effect outside battle; e.g. xp scrolls, ryo bags
//   boost       → temporary battle buff (attack/defense multiplier for N turns)

export default [

  // ── HEALTH POTIONS ───────────────────────────────────────────────────────────
  {
    id: "small_hp_potion",
    name: "Small Health Potion",
    type: "consumable",
    price: 150,
    effect: { hp: 50 },
    description: "Restores 50 HP. Good for early missions.",
  },
  {
    id: "medium_hp_potion",
    name: "Medium Health Potion",
    type: "consumable",
    price: 300,
    effect: { hp: 120 },
    description: "Restores 120 HP.",
  },
  {
    id: "large_hp_potion",
    name: "Large Health Potion",
    type: "consumable",
    price: 600,
    effect: { hp: 250 },
    description: "Restores 250 HP.",
  },
  {
    id: "full_heal",
    name: "Full Heal Elixir",
    type: "consumable",
    price: 2000,
    effect: { hp: 9999 },
    description: "Fully restores all HP. Rare and expensive.",
  },
  {
    id: "antidote",
    name: "Antidote",
    type: "consumable",
    price: 180,
    effect: { hp: 30 },
    description: "Cures minor poison. Restores 30 HP.",
  },
  {
    id: "blood_pill",
    name: "Blood Pill",
    type: "consumable",
    price: 450,
    effect: { hp: 180 },
    description: "A forbidden pill used by ANBU. Restores 180 HP at a cost.",
  },

  // ── CHAKRA POTIONS ───────────────────────────────────────────────────────────
  {
    id: "small_chakra_potion",
    name: "Small Chakra Potion",
    type: "consumable",
    price: 200,
    effect: { chakra: 50 },
    description: "Restores 50 Chakra.",
  },
  {
    id: "chakra_potion",
    name: "Chakra Potion",
    type: "consumable",
    price: 350,
    effect: { chakra: 100 },
    description: "Restores 100 Chakra.",
  },
  {
    id: "large_chakra_potion",
    name: "Large Chakra Potion",
    type: "consumable",
    price: 700,
    effect: { chakra: 220 },
    description: "Restores 220 Chakra.",
  },
  {
    id: "chakra_crystal",
    name: "Chakra Crystal",
    type: "consumable",
    price: 1200,
    effect: { chakra: 400 },
    description: "Rare crystal brimming with pure chakra. Restores 400 Chakra.",
  },

  // ── COMBO POTIONS ─────────────────────────────────────────────────────────────
  {
    id: "soldier_pill",
    name: "Soldier Pill",
    type: "consumable",
    price: 500,
    effect: { hp: 100, chakra: 100 },
    description: "Restores both HP and Chakra. Standard shinobi field ration.",
  },
  {
    id: "military_pill",
    name: "Military Ration Pill",
    type: "consumable",
    price: 900,
    effect: { hp: 200, chakra: 200 },
    description: "An upgraded ration pill used by elite squads.",
  },
  {
    id: "akimichi_pill_1",
    name: "Akimichi Green Pill",
    type: "consumable",
    price: 1500,
    effect: { hp: 350, chakra: 150 },
    description: "The first of the Three Coloured Pills. Massive HP boost.",
  },
  {
    id: "akimichi_pill_2",
    name: "Akimichi Yellow Pill",
    type: "consumable",
    price: 2500,
    effect: { hp: 500, chakra: 300 },
    description: "The second Coloured Pill. Extreme power at great risk.",
  },
  {
    id: "elixir_of_life",
    name: "Elixir of Life",
    type: "consumable",
    price: 3500,
    effect: { hp: 9999, chakra: 9999 },
    description: "Fully restores HP and Chakra. Said to be brewed by the Sage himself.",
  },

  // ── BATTLE ITEMS (offensive) ─────────────────────────────────────────────────
  {
    id: "kunai",
    name: "Kunai",
    type: "battle",
    price: 120,
    damage: 40,
    description: "A basic thrown kunai. Deals 40 damage.",
  },
  {
    id: "shuriken",
    name: "Shuriken",
    type: "battle",
    price: 150,
    damage: 55,
    description: "Sharp throwing star. Deals 55 damage.",
  },
  {
    id: "explosive_tag",
    name: "Explosive Tag",
    type: "battle",
    price: 600,
    damage: 130,
    description: "A paper bomb. Deals 130 damage.",
  },
  {
    id: "smoke_bomb",
    name: "Smoke Bomb",
    type: "battle",
    price: 250,
    damage: 20,
    description: "Deals 20 damage and obscures vision (-10% opponent accuracy this round).",
  },
  {
    id: "poison_needle",
    name: "Poison Needle",
    type: "battle",
    price: 400,
    damage: 70,
    description: "A senbon coated in poison. Deals 70 damage.",
  },
  {
    id: "giant_shuriken",
    name: "Fuma Shuriken",
    type: "battle",
    price: 900,
    damage: 200,
    description: "The massive folding shuriken of the Fuma clan. Deals 200 damage.",
  },
  {
    id: "explosive_kunai",
    name: "Explosive Kunai",
    type: "battle",
    price: 800,
    damage: 180,
    description: "A kunai rigged with explosive tags. Deals 180 damage.",
  },
  {
    id: "thunder_tag",
    name: "Thunder Flash Tag",
    type: "battle",
    price: 1100,
    damage: 260,
    description: "An advanced explosive tag infused with lightning chakra. Deals 260 damage.",
  },
  {
    id: "wind_blade",
    name: "Wind Blade Scroll",
    type: "battle",
    price: 1400,
    damage: 320,
    description: "Releases a razor-sharp wind blade. Deals 320 damage.",
  },
  {
    id: "bijuu_bomb_shard",
    name: "Bijuu Bomb Shard",
    type: "battle",
    price: 5000,
    damage: 750,
    description: "A crystallised fragment of a tailed-beast bomb. Catastrophic damage.",
  },

  // ── WEAPONS (passive attack boost — displayed in shop) ───────────────────────
  {
    id: "iron_kunai",
    name: "Iron Kunai Set",
    type: "weapon",
    price: 350,
    attack: 10,
    description: "Reinforced kunai that increase attack by 10.",
  },
  {
    id: "chakra_blade",
    name: "Chakra Blade",
    type: "weapon",
    price: 1800,
    attack: 30,
    description: "A blade that channels chakra. Attack +30.",
  },
  {
    id: "seven_swords",
    name: "Sword of the Mist",
    type: "weapon",
    price: 4000,
    attack: 60,
    description: "A legendary blade wielded by the Seven Swordsmen. Attack +60.",
  },
  {
    id: "kubikiribocho",
    name: "Kubikiribōchō",
    type: "weapon",
    price: 8000,
    attack: 100,
    description: "Zabuza's great sword — regenerates by absorbing iron from blood. Attack +100.",
  },

  // ── ARMOR (passive defense boost) ─────────────────────────────────────────────
  {
    id: "flak_jacket",
    name: "Flak Jacket",
    type: "armor",
    price: 500,
    defense: 15,
    description: "Standard Konoha flak jacket. Defense +15.",
  },
  {
    id: "anbu_vest",
    name: "ANBU Vest",
    type: "armor",
    price: 2000,
    defense: 35,
    description: "Reinforced ANBU-grade armor. Defense +35.",
  },
  {
    id: "samurai_armor",
    name: "Samurai Armor",
    type: "armor",
    price: 5000,
    defense: 70,
    description: "Heavy Land-of-Iron samurai plate. Defense +70.",
  },
  {
    id: "sage_cloak",
    name: "Sage Mode Cloak",
    type: "armor",
    price: 10000,
    defense: 120,
    description: "The cloak worn by a sage. Defense +120 and natural energy ward.",
  },

  // ── XP / SPECIAL ITEMS ────────────────────────────────────────────────────────
  {
    id: "scroll_of_knowledge",
    name: "Scroll of Knowledge",
    type: "special",
    price: 2000,
    xp: 500,
    description: "Instantly grants 500 XP.",
  },
  {
    id: "forbidden_scroll",
    name: "Forbidden Scroll",
    type: "special",
    price: 5000,
    xp: 1500,
    description: "A forbidden jutsu scroll. Grants 1500 XP.",
  },
  {
    id: "sage_scroll",
    name: "Sage Art Scroll",
    type: "special",
    price: 12000,
    xp: 4000,
    description: "Ancient scroll from Mount Myōboku. Grants 4000 XP.",
  },
  {
    id: "ryo_bag_small",
    name: "Small Ryo Bag",
    type: "special",
    price: 500,
    ryo: 750,
    description: "A bag of ryo. Instantly grants 750 Ryo.",
  },
  {
    id: "ryo_bag_large",
    name: "Large Ryo Bag",
    type: "special",
    price: 1500,
    ryo: 2500,
    description: "A heavy bag of ryo. Instantly grants 2500 Ryo.",
  },
  {
    id: "daimyo_chest",
    name: "Daimyo's Chest",
    type: "special",
    price: 8000,
    ryo: 15000,
    description: "A chest from a Fire Country Daimyo. Grants 15,000 Ryo.",
  },
  {
    id: "mission_voucher",
    name: "Mission Voucher",
    type: "special",
    price: 1000,
    xp: 300,
    ryo: 500,
    description: "A bounty voucher worth 300 XP and 500 Ryo.",
  },

  // ── BOOST ITEMS (battle buffs) ────────────────────────────────────────────────
  {
    id: "red_chilli_pill",
    name: "Red Chilli Pill",
    type: "consumable",
    price: 700,
    effect: { hp: 60 },
    attackBoost: 20,
    boostTurns: 3,
    description: "Restores 60 HP and temporarily boosts attack by 20 for 3 turns.",
  },
  {
    id: "iron_skin_seal",
    name: "Iron Skin Seal",
    type: "consumable",
    price: 800,
    effect: { hp: 40 },
    defenseBoost: 25,
    boostTurns: 3,
    description: "Restores 40 HP and boosts defense by 25 for 3 turns.",
  },
  {
    id: "speed_seal",
    name: "Speed Seal",
    type: "consumable",
    price: 600,
    effect: { chakra: 50 },
    speedBoost: 20,
    boostTurns: 2,
    description: "Restores 50 Chakra and boosts speed by 20 for 2 turns.",
  },
  {
    id: "berserker_pill",
    name: "Berserker Pill",
    type: "consumable",
    price: 1800,
    effect: { hp: 100 },
    attackBoost: 50,
    boostTurns: 4,
    description: "Restores 100 HP and massively boosts attack by 50 for 4 turns.",
  },
];
