// lib/naruto/jutsu.js

export default [
  {
    id: "basic_taijutsu",
    name: "Basic Taijutsu",
    type: "Taijutsu",
    rank: "E",
    level: 1,
    damage: 15,
    chakra: 0,
    accuracy: 100,
    cooldown: 0,
    clan: null
  },
  {
    id: "shadow_clone",
    name: "Shadow Clone Jutsu",
    type: "Ninjutsu",
    rank: "C",
    level: 5,
    damage: 25,
    chakra: 20,
    accuracy: 95,
    cooldown: 2,
    clan: null
  },
  {
    id: "fireball",
    name: "Fire Style: Fireball Jutsu",
    type: "Ninjutsu",
    rank: "C",
    level: 10,
    damage: 40,
    chakra: 30,
    accuracy: 90,
    cooldown: 3,
    clan: "Uchiha"
  },
  {
    id: "water_dragon",
    name: "Water Dragon Jutsu",
    type: "Ninjutsu",
    rank: "B",
    level: 15,
    damage: 55,
    chakra: 40,
    accuracy: 88,
    cooldown: 3,
    clan: null
  },
  {
    id: "chidori",
    name: "Chidori",
    type: "Ninjutsu",
    rank: "A",
    level: 25,
    damage: 70,
    chakra: 50,
    accuracy: 85,
    cooldown: 4,
    clan: null
  },
  {
    id: "rasengan",
    name: "Rasengan",
    type: "Ninjutsu",
    rank: "A",
    level: 30,
    damage: 80,
    chakra: 55,
    accuracy: 90,
    cooldown: 4,
    clan: null
  },
  {
    id: "sand_coffin",
    name: "Sand Coffin",
    type: "Ninjutsu",
    rank: "A",
    level: 20,
    damage: 65,
    chakra: 45,
    accuracy: 85,
    cooldown: 3,
    clan: null
  },
  {
    id: "shadow_possession",
    name: "Shadow Possession Jutsu",
    type: "Ninjutsu",
    rank: "B",
    level: 18,
    damage: 30,
    chakra: 35,
    accuracy: 90,
    cooldown: 3,
    clan: "Nara"
  },
  {
    id: "gentle_fist",
    name: "Gentle Fist",
    type: "Taijutsu",
    rank: "B",
    level: 15,
    damage: 50,
    chakra: 25,
    accuracy: 92,
    cooldown: 2,
    clan: "Hyuga"
  },
  {
    id: "wood_style",
    name: "Wood Style: Wood Wall",
    type: "Ninjutsu",
    rank: "S",
    level: 40,
    damage: 95,
    chakra: 70,
    accuracy: 88,
    cooldown: 5,
    clan: "Senju"
  },
  {
    id: "rasenshuriken",
    name: "Rasenshuriken",
    type: "Ninjutsu",
    rank: "S",
    level: 50,
    damage: 120,
    chakra: 80,
    accuracy: 85,
    cooldown: 6,
    clan: null
  },
  {
    id: "amaterasu",
    name: "Amaterasu",
    type: "Ninjutsu",
    rank: "S",
    level: 60,
    damage: 130,
    chakra: 90,
    accuracy: 80,
    cooldown: 6,
    clan: "Uchiha"
  },
  {
    id: "bijuu_bomb",
    name: "Bijuu Bomb",
    type: "Ninjutsu",
    rank: "S",
    level: 80,
    damage: 160,
    chakra: 110,
    accuracy: 78,
    cooldown: 7,
    clan: null
  },
];
