// lib/jutsu.js — Expanded jutsu roster (Dattebayo-API-inspired)
// id, name, type, rank (E/D/C/B/A/S), level, damage, chakra, accuracy, cooldown, clan

export default [
  // ── Rank E / D (Starter) ──────────────────────────────────────────────────────
  {
    id: "basic_taijutsu",
    name: "Basic Taijutsu",
    type: "Taijutsu",
    rank: "E",
    level: 1,
    damage: 15,
    chakra: 0,
    accuracy: 100,
    cooldown: 0,
    clan: null,
  },
  {
    id: "clone_body_blow",
    name: "Clone Body Blow",
    type: "Taijutsu",
    rank: "D",
    level: 3,
    damage: 22,
    chakra: 5,
    accuracy: 95,
    cooldown: 0,
    clan: null,
  },
  {
    id: "substitution",
    name: "Substitution Jutsu",
    type: "Ninjutsu",
    rank: "D",
    level: 3,
    damage: 0,
    chakra: 10,
    accuracy: 100,
    cooldown: 3,
    clan: null,
    effect: "dodge",
    description: "Swap with a nearby object to avoid an attack.",
  },

  // ── Rank C ────────────────────────────────────────────────────────────────────
  {
    id: "shadow_clone",
    name: "Shadow Clone Jutsu",
    type: "Ninjutsu",
    rank: "C",
    level: 5,
    damage: 25,
    chakra: 20,
    accuracy: 95,
    cooldown: 2,
    clan: null,
  },
  {
    id: "fireball",
    name: "Fire Style: Fireball Jutsu",
    type: "Ninjutsu",
    rank: "C",
    level: 10,
    damage: 40,
    chakra: 30,
    accuracy: 90,
    cooldown: 3,
    clan: "Uchiha",
  },
  {
    id: "earth_wall",
    name: "Earth Style: Earth Wall",
    type: "Ninjutsu",
    rank: "C",
    level: 8,
    damage: 20,
    chakra: 25,
    accuracy: 100,
    cooldown: 2,
    clan: null,
  },
  {
    id: "water_bullet",
    name: "Water Style: Water Bullet",
    type: "Ninjutsu",
    rank: "C",
    level: 9,
    damage: 35,
    chakra: 28,
    accuracy: 92,
    cooldown: 2,
    clan: null,
  },
  {
    id: "wind_cutter",
    name: "Wind Style: Wind Cutter",
    type: "Ninjutsu",
    rank: "C",
    level: 10,
    damage: 38,
    chakra: 30,
    accuracy: 90,
    cooldown: 2,
    clan: null,
  },
  {
    id: "lightning_straight",
    name: "Lightning Style: Lightning Straight",
    type: "Ninjutsu",
    rank: "C",
    level: 10,
    damage: 40,
    chakra: 32,
    accuracy: 88,
    cooldown: 3,
    clan: null,
  },

  // ── Rank B ────────────────────────────────────────────────────────────────────
  {
    id: "water_dragon",
    name: "Water Dragon Jutsu",
    type: "Ninjutsu",
    rank: "B",
    level: 15,
    damage: 55,
    chakra: 40,
    accuracy: 88,
    cooldown: 3,
    clan: null,
  },
  {
    id: "shadow_possession",
    name: "Shadow Possession Jutsu",
    type: "Ninjutsu",
    rank: "B",
    level: 18,
    damage: 30,
    chakra: 35,
    accuracy: 90,
    cooldown: 3,
    clan: "Nara",
  },
  {
    id: "gentle_fist",
    name: "Gentle Fist",
    type: "Taijutsu",
    rank: "B",
    level: 15,
    damage: 50,
    chakra: 25,
    accuracy: 92,
    cooldown: 2,
    clan: "Hyuga",
  },
  {
    id: "sand_coffin",
    name: "Sand Coffin",
    type: "Ninjutsu",
    rank: "B",
    level: 20,
    damage: 60,
    chakra: 45,
    accuracy: 85,
    cooldown: 3,
    clan: null,
  },
  {
    id: "insect_swarm",
    name: "Insect Swarm",
    type: "Ninjutsu",
    rank: "B",
    level: 17,
    damage: 45,
    chakra: 40,
    accuracy: 88,
    cooldown: 3,
    clan: "Aburame",
  },
  {
    id: "expansion_jutsu",
    name: "Multi-Size Technique",
    type: "Taijutsu",
    rank: "B",
    level: 15,
    damage: 65,
    chakra: 35,
    accuracy: 85,
    cooldown: 3,
    clan: "Akimichi",
  },
  {
    id: "fang_over_fang",
    name: "Fang Over Fang",
    type: "Taijutsu",
    rank: "B",
    level: 18,
    damage: 58,
    chakra: 30,
    accuracy: 87,
    cooldown: 3,
    clan: "Inuzuka",
  },
  {
    id: "mind_transfer",
    name: "Mind Transfer Jutsu",
    type: "Ninjutsu",
    rank: "B",
    level: 20,
    damage: 35,
    chakra: 50,
    accuracy: 80,
    cooldown: 4,
    clan: "Yamanaka",
  },
  {
    id: "flying_thunder_god",
    name: "Flying Thunder God",
    type: "Ninjutsu",
    rank: "S",
    level: 80,
    damage: 110,
    chakra: 90,
    accuracy: 95,
    cooldown: 5,
    clan: "Namikaze",
  },

  // ── Rank A ────────────────────────────────────────────────────────────────────
  {
    id: "chidori",
    name: "Chidori",
    type: "Ninjutsu",
    rank: "A",
    level: 25,
    damage: 70,
    chakra: 50,
    accuracy: 85,
    cooldown: 4,
    clan: null,
  },
  {
    id: "rasengan",
    name: "Rasengan",
    type: "Ninjutsu",
    rank: "A",
    level: 30,
    damage: 80,
    chakra: 55,
    accuracy: 90,
    cooldown: 4,
    clan: null,
  },
  {
    id: "great_fireball",
    name: "Fire Style: Great Fireball",
    type: "Ninjutsu",
    rank: "A",
    level: 28,
    damage: 75,
    chakra: 55,
    accuracy: 88,
    cooldown: 4,
    clan: "Uchiha",
  },
  {
    id: "lion_combo",
    name: "Lion Combo",
    type: "Taijutsu",
    rank: "A",
    level: 32,
    damage: 78,
    chakra: 30,
    accuracy: 88,
    cooldown: 4,
    clan: null,
  },
  {
    id: "bone_blade",
    name: "Dead Bone Pulse: Bone Blade",
    type: "Taijutsu",
    rank: "A",
    level: 30,
    damage: 82,
    chakra: 40,
    accuracy: 87,
    cooldown: 4,
    clan: "Kaguya",
  },
  {
    id: "eight_gates",
    name: "Eight Gates Formation",
    type: "Taijutsu",
    rank: "A",
    level: 40,
    damage: 90,
    chakra: 60,
    accuracy: 85,
    cooldown: 5,
    clan: null,
  },
  {
    id: "water_shark_bomb",
    name: "Water Shark Bomb",
    type: "Ninjutsu",
    rank: "A",
    level: 35,
    damage: 85,
    chakra: 60,
    accuracy: 86,
    cooldown: 4,
    clan: null,
  },
  {
    id: "hydration_technique",
    name: "Hydration Technique",
    type: "Ninjutsu",
    rank: "A",
    level: 30,
    damage: 60,
    chakra: 55,
    accuracy: 90,
    cooldown: 4,
    clan: "Hōzuki",
  },
  {
    id: "shadow_sewing",
    name: "Shadow Sewing Jutsu",
    type: "Ninjutsu",
    rank: "A",
    level: 35,
    damage: 65,
    chakra: 55,
    accuracy: 88,
    cooldown: 4,
    clan: "Nara",
  },
  {
    id: "eight_trigrams_64",
    name: "Eight Trigrams: 64 Palms",
    type: "Taijutsu",
    rank: "A",
    level: 40,
    damage: 90,
    chakra: 50,
    accuracy: 90,
    cooldown: 5,
    clan: "Hyuga",
  },

  // ── Rank S ────────────────────────────────────────────────────────────────────
  {
    id: "wood_style",
    name: "Wood Style: Wood Wall",
    type: "Ninjutsu",
    rank: "S",
    level: 40,
    damage: 95,
    chakra: 70,
    accuracy: 88,
    cooldown: 5,
    clan: "Senju",
  },
  {
    id: "rasenshuriken",
    name: "Rasenshuriken",
    type: "Ninjutsu",
    rank: "S",
    level: 50,
    damage: 120,
    chakra: 80,
    accuracy: 85,
    cooldown: 6,
    clan: null,
  },
  {
    id: "amaterasu",
    name: "Amaterasu",
    type: "Ninjutsu",
    rank: "S",
    level: 60,
    damage: 130,
    chakra: 90,
    accuracy: 80,
    cooldown: 6,
    clan: "Uchiha",
  },
  {
    id: "susanoo",
    name: "Susanoo",
    type: "Ninjutsu",
    rank: "S",
    level: 70,
    damage: 140,
    chakra: 100,
    accuracy: 82,
    cooldown: 6,
    clan: "Uchiha",
  },
  {
    id: "bijuu_bomb",
    name: "Bijuu Bomb",
    type: "Ninjutsu",
    rank: "S",
    level: 80,
    damage: 160,
    chakra: 120,
    accuracy: 78,
    cooldown: 7,
    clan: null,
  },
  {
    id: "truth_seeking_orbs",
    name: "Truth-Seeking Orbs",
    type: "Ninjutsu",
    rank: "S",
    level: 90,
    damage: 175,
    chakra: 140,
    accuracy: 80,
    cooldown: 7,
    clan: null,
  },
  {
    id: "kama_absorption",
    name: "Kāma: Jutsu Absorption",
    type: "Ninjutsu",
    rank: "S",
    level: 60,
    damage: 100,
    chakra: 80,
    accuracy: 85,
    cooldown: 5,
    clan: "Ōtsutsuki",
  },
  {
    id: "infinite_tsukuyomi",
    name: "Infinite Tsukuyomi",
    type: "Genjutsu",
    rank: "S",
    level: 100,
    damage: 200,
    chakra: 180,
    accuracy: 75,
    cooldown: 8,
    clan: "Uchiha",
  },
];
