/**
 * Store profile backgrounds without relying on an external anonymous uploader.
 *
 * Profile cards are generated by the bot process itself, so a data image is
 * both more reliable and more durable than a third-party URL that can expire
 * or reject the runtime's IP address.
 */

function detectImageMime(buffer) {
  if (buffer.length >= 3 && buffer.subarray(0, 3).equals(Buffer.from([0xff, 0xd8, 0xff]))) {
    return "image/jpeg";
  }
  if (
    buffer.length >= 8 &&
    buffer.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))
  ) {
    return "image/png";
  }
  if (buffer.length >= 6 && ["GIF87a", "GIF89a"].includes(buffer.subarray(0, 6).toString("ascii"))) {
    return "image/gif";
  }
  if (
    buffer.length >= 12 &&
    buffer.subarray(0, 4).toString("ascii") === "RIFF" &&
    buffer.subarray(8, 12).toString("ascii") === "WEBP"
  ) {
    return "image/webp";
  }
  return null;
}

export function encodeProfileBackground(buffer) {
  if (!Buffer.isBuffer(buffer) || buffer.length === 0) {
    throw new Error("empty profile background");
  }

  const mime = detectImageMime(buffer);
  if (!mime) {
    throw new Error("unsupported profile background format");
  }

  return `data:${mime};base64,${buffer.toString("base64")}`;
}