/**
 * KELIN MD — Dragon Ball Z villain enemies
 * Used by dhunt.js for PvE encounters.
 * Villains spawn based on player level.
 */
export default [
  // ── Level 1–9 (Earthling) ──────────────────────────────────────────────────
  {
    name: "Saibaman",
    level: 1,
    hp: 70, maxHp: 70, ki: 20,
    attack: 9, defense: 4, speed: 7,
    techniques: [],
    xpReward: 25, zeniReward: 60,
    apiName: "Raditz",
    description: "A plant-based soldier from Vegeta's army.",
  },
  {
    name: "Frieza Soldier",
    level: 3,
    hp: 90, maxHp: 90, ki: 30,
    attack: 13, defense: 6, speed: 9,
    techniques: [],
    xpReward: 40, zeniReward: 100,
    apiName: "Ginyu",
    description: "A low-ranking member of Frieza's galactic army.",
  },
  {
    name: "Cui",
    level: 5,
    hp: 120, maxHp: 120, ki: 40,
    attack: 18, defense: 10, speed: 13,
    techniques: ["renzoku_energy_dan"],
    xpReward: 60, zeniReward: 150,
    apiName: "Zarbon",
    description: "A rival of Vegeta serving in Frieza's army.",
  },

  // ── Level 10–24 (Z Fighter) ────────────────────────────────────────────────
  {
    name: "Nappa",
    level: 10,
    hp: 160, maxHp: 160, ki: 60,
    attack: 24, defense: 16, speed: 14,
    techniques: ["double_sunday"],
    xpReward: 90, zeniReward: 220,
    apiName: "Vegeta",
    description: "Vegeta's large Saiyan companion — brutal and powerful.",
  },
  {
    name: "Dodoria",
    level: 12,
    hp: 180, maxHp: 180, ki: 65,
    attack: 28, defense: 18, speed: 12,
    techniques: ["renzoku_energy_dan"],
    xpReward: 110, zeniReward: 280,
    apiName: "Dodoria",
    description: "Frieza's beefy, savage right-hand enforcer.",
  },
  {
    name: "Zarbon",
    level: 15,
    hp: 210, maxHp: 210, ki: 80,
    attack: 34, defense: 22, speed: 20,
    techniques: ["double_sunday", "renzoku_energy_dan"],
    xpReward: 140, zeniReward: 350,
    apiName: "Zarbon",
    description: "An elegant but brutal warrior — he has a monstrous true form.",
  },

  // ── Level 25–39 (Elite Warrior) ────────────────────────────────────────────
  {
    name: "Raditz",
    level: 25,
    hp: 270, maxHp: 270, ki: 110,
    attack: 42, defense: 28, speed: 26,
    techniques: ["double_sunday", "renzoku_energy_dan"],
    xpReward: 185, zeniReward: 460,
    apiName: "Raditz",
    description: "Goku's elder brother. A low-class Saiyan warrior.",
  },
  {
    name: "Ginyu",
    level: 30,
    hp: 330, maxHp: 330, ki: 140,
    attack: 50, defense: 35, speed: 32,
    techniques: ["renzoku_energy_dan", "destructo_disc"],
    xpReward: 230, zeniReward: 580,
    apiName: "Ginyu",
    description: "Leader of the Ginyu Force — flamboyant but deadly.",
  },
  {
    name: "Frieza (1st Form)",
    level: 35,
    hp: 390, maxHp: 390, ki: 170,
    attack: 58, defense: 42, speed: 38,
    techniques: ["destructo_disc", "renzoku_energy_dan"],
    xpReward: 280, zeniReward: 700,
    apiName: "Freezer",
    description: "The galactic emperor in his most restrained form — still terrifying.",
  },

  // ── Level 40–59 (Super Warrior) ────────────────────────────────────────────
  {
    name: "Android 19",
    level: 40,
    hp: 460, maxHp: 460, ki: 200,
    attack: 66, defense: 50, speed: 42,
    techniques: ["destructo_disc", "renzoku_energy_dan"],
    xpReward: 340, zeniReward: 850,
    apiName: "Android 17",
    description: "An energy-absorbing android created by Dr. Gero.",
  },
  {
    name: "Android 20 (Dr. Gero)",
    level: 44,
    hp: 500, maxHp: 500, ki: 220,
    attack: 72, defense: 55, speed: 44,
    techniques: ["renzoku_energy_dan", "energy_shield"],
    xpReward: 380, zeniReward: 950,
    apiName: "Android 17",
    description: "Dr. Gero — the mad scientist who turned himself into an android.",
  },
  {
    name: "Cell (Imperfect)",
    level: 50,
    hp: 580, maxHp: 580, ki: 260,
    attack: 82, defense: 62, speed: 52,
    techniques: ["renzoku_energy_dan", "kamehameha"],
    xpReward: 440, zeniReward: 1100,
    apiName: "Celula",
    description: "Cell in his initial absorption stage — already terrifyingly powerful.",
  },
  {
    name: "Frieza (Final Form)",
    level: 55,
    hp: 650, maxHp: 650, ki: 300,
    attack: 90, defense: 70, speed: 62,
    techniques: ["death_ball", "renzoku_energy_dan"],
    xpReward: 500, zeniReward: 1250,
    apiName: "Freezer",
    description: "Frieza's true final form — the most feared being in the universe.",
  },

  // ── Level 60–84 (Super Saiyan) ─────────────────────────────────────────────
  {
    name: "Cell (Semi-Perfect)",
    level: 62,
    hp: 740, maxHp: 740, ki: 340,
    attack: 100, defense: 78, speed: 70,
    techniques: ["kamehameha", "renzoku_energy_dan", "energy_shield"],
    xpReward: 580, zeniReward: 1450,
    apiName: "Celula",
    description: "After absorbing Android 17 — Cell's power doubles!",
  },
  {
    name: "Cell (Perfect)",
    level: 72,
    hp: 870, maxHp: 870, ki: 400,
    attack: 115, defense: 90, speed: 82,
    techniques: ["kamehameha", "death_ball", "energy_shield"],
    xpReward: 680, zeniReward: 1700,
    apiName: "Celula",
    description: "The ultimate perfect form of Cell. Arrogant and godlike.",
  },

  // ── Level 85–119 (Super Saiyan 2) ─────────────────────────────────────────
  {
    name: "Majin Buu",
    level: 88,
    hp: 1000, maxHp: 1000, ki: 460,
    attack: 130, defense: 102, speed: 90,
    techniques: ["kamehameha", "energy_shield", "destructo_disc"],
    xpReward: 800, zeniReward: 2000,
    apiName: "Majin Buu",
    description: "The pink terror — ancient evil sealed away for millennia. Nearly unkillable.",
  },
  {
    name: "Super Buu",
    level: 100,
    hp: 1180, maxHp: 1180, ki: 540,
    attack: 148, defense: 116, speed: 105,
    techniques: ["kamehameha", "spirit_bomb", "energy_shield"],
    xpReward: 940, zeniReward: 2350,
    apiName: "Majin Buu",
    description: "Buu after absorbing Gotenks — exponentially more dangerous.",
  },

  // ── Level 120+ (Super Saiyan 3 / God) ────────────────────────────────────
  {
    name: "Janemba",
    level: 120,
    hp: 1380, maxHp: 1380, ki: 640,
    attack: 170, defense: 134, speed: 125,
    techniques: ["death_ball", "spirit_bomb", "renzoku_energy_dan"],
    xpReward: 1100, zeniReward: 2750,
    apiName: "Janemba",
    description: "A demonic being of pure evil energy from the Underworld.",
  },
  {
    name: "Broly",
    level: 140,
    hp: 1620, maxHp: 1620, ki: 760,
    attack: 195, defense: 152, speed: 140,
    techniques: ["kamehameha", "death_ball", "energy_shield"],
    xpReward: 1300, zeniReward: 3250,
    apiName: "Broly",
    description: "The Legendary Super Saiyan — power that grows without limit. KAKAROT!!!",
  },
  {
    name: "Kid Buu",
    level: 160,
    hp: 1900, maxHp: 1900, ki: 900,
    attack: 220, defense: 168, speed: 160,
    techniques: ["spirit_bomb", "kamehameha", "death_ball"],
    xpReward: 1550, zeniReward: 3850,
    apiName: "Majin Buu",
    description: "The original, purest — and most dangerous — form of Majin Buu.",
  },
];
